/* Copyright 2011 Google */function tn_aa(a){return a in tn_ba?tn_ba[a]:tn_ba[a]=-1!=navigator.userAgent.toLowerCase().indexOf(a)}var tn_ba={},tn_ca={ua:function(a){return a.document.body.scrollTop},va:function(a){return a.document.documentElement.scrollTop},W:function(a){return a.pageYOffset}},tn_da={ua:function(a){return a.document.body.scrollLeft},va:function(a){return a.document.documentElement.scrollLeft},W:function(a){return a.pageXOffset}};
function tn_ea(a,b){try{if(tn_aa("safari")||tn_aa("konqueror"))return b.W(a);if(!window.opera&&"compatMode"in a.document&&"CSS1Compat"==a.document.compatMode)return b.va(a);if(tn_aa("msie")&&!window.opera)return b.ua(a)}catch(c){}return b.W(a)};function tn_a(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||null}tn_a.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};tn_a.prototype.clone=function(){return new tn_a(this.x,this.y,this.coordinateFrame)};function tn_fa(a,b){this.dx=a;this.dy=b}tn_fa.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function tn_b(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||null}
tn_b.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};tn_b.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};tn_b.prototype.clone=function(){return new tn_b(this.x,this.y,this.w,this.h,this.coordinateFrame)};function tn_ga(a){function b(b){for(var c=a.offsetParent;c&&c.offsetParent;c=c.offsetParent)c.scrollLeft&&(b.x-=c.scrollLeft),c.scrollTop&&(b.y-=c.scrollTop)}if(!a)return null;var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:a.ownerDocument&&a.ownerDocument.defaultView?a.ownerDocument.defaultView:window;if(a.getBoundingClientRect){var d=a.getBoundingClientRect();return new tn_b(d.left+tn_ea(c,tn_da),d.top+tn_ea(c,tn_ca),d.right-d.left,d.bottom-d.top,c)}if(a.ownerDocument&&
a.ownerDocument.getBoxObjectFor)return d=a.ownerDocument.getBoxObjectFor(a),c=new tn_b(d.x,d.y,d.width,d.height,c),b(c),c;for(var e=d=0,f=a;f.offsetParent;f=f.offsetParent)d+=f.offsetLeft,e+=f.offsetTop;c=new tn_b(d,e,a.offsetWidth,a.offsetHeight,c);b(c);return c};var tn_c=function(){for(var a=[" ","\u0120",-1,"!","\u0120",-1,"\u0120","\u0120",0,"\u0121","\u0120",-1,"\u0121","\u0120|\u0121",0,"\u0122","\u0120|\u0121",-1,"\u0120","[\u0120]",0,"\u0121","[\u0120]",-1,"\u0121","[\u0120\u0121]",0,"\u0122","[\u0120\u0121]",-1,"\u0121","[\u0120-\u0121]",0,"\u0122","[\u0120-\u0121]",-1],b=0;b<a.length;b+=3)if(a[b].search(RegExp(a[b+1]))!=a[b+2])return!1;return!0}(),tn_ha=tn_c?"A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3":
"A-Za-z",tn_ia=tn_c?"\u4e00-\u9fa5\u3007\u3021-\u3029":"",tn_ja=tn_c?"\u0300-\u0345\u0360-\u0361\u0483-\u0486\u0591-\u05a1\u05a3-\u05b9\u05bb-\u05bd\u05bf\u05c1-\u05c2\u05c4\u064b-\u0652\u0670\u06d6-\u06dc\u06dd-\u06df\u06e0-\u06e4\u06e7-\u06e8\u06ea-\u06ed\u0901-\u0903\u093c\u093e-\u094c\u094d\u0951-\u0954\u0962-\u0963\u0981-\u0983\u09bc\u09be\u09bf\u09c0-\u09c4\u09c7-\u09c8\u09cb-\u09cd\u09d7\u09e2-\u09e3\u0a02\u0a3c\u0a3e\u0a3f\u0a40-\u0a42\u0a47-\u0a48\u0a4b-\u0a4d\u0a70-\u0a71\u0a81-\u0a83\u0abc\u0abe-\u0ac5\u0ac7-\u0ac9\u0acb-\u0acd\u0b01-\u0b03\u0b3c\u0b3e-\u0b43\u0b47-\u0b48\u0b4b-\u0b4d\u0b56-\u0b57\u0b82-\u0b83\u0bbe-\u0bc2\u0bc6-\u0bc8\u0bca-\u0bcd\u0bd7\u0c01-\u0c03\u0c3e-\u0c44\u0c46-\u0c48\u0c4a-\u0c4d\u0c55-\u0c56\u0c82-\u0c83\u0cbe-\u0cc4\u0cc6-\u0cc8\u0cca-\u0ccd\u0cd5-\u0cd6\u0d02-\u0d03\u0d3e-\u0d43\u0d46-\u0d48\u0d4a-\u0d4d\u0d57\u0e31\u0e34-\u0e3a\u0e47-\u0e4e\u0eb1\u0eb4-\u0eb9\u0ebb-\u0ebc\u0ec8-\u0ecd\u0f18-\u0f19\u0f35\u0f37\u0f39\u0f3e\u0f3f\u0f71-\u0f84\u0f86-\u0f8b\u0f90-\u0f95\u0f97\u0f99-\u0fad\u0fb1-\u0fb7\u0fb9\u20d0-\u20dc\u20e1\u302a-\u302f\u3099\u309a":
"",tn_ka=tn_c?"0-9\u0660-\u0669\u06f0-\u06f9\u0966-\u096f\u09e6-\u09ef\u0a66-\u0a6f\u0ae6-\u0aef\u0b66-\u0b6f\u0be7-\u0bef\u0c66-\u0c6f\u0ce6-\u0cef\u0d66-\u0d6f\u0e50-\u0e59\u0ed0-\u0ed9\u0f20-\u0f29":"0-9",tn_la=tn_c?"\u00b7\u02d0\u02d1\u0387\u0640\u0e46\u0ec6\u3005\u3031-\u3035\u309d-\u309e\u30fc-\u30fe":"",tn_ma=tn_ha+tn_ia,tn_na=tn_ma+tn_ka+"\\._:"+tn_ja+tn_la+"-",tn_oa="["+tn_ma+"_:]["+tn_na+"]*",tn_pa="&"+tn_oa+";",tn_qa=tn_pa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ra='"(([^<&"]|'+tn_qa+")*)\"|'(([^<&']|"+
tn_qa+")*)'",tn_sa="("+tn_oa+")([ \t\r\n]+)?=([ \t\r\n]+)?("+tn_ra+")",tn_ta=tn_c?":A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd":":A-Z_a-z",tn_ua=tn_ta+(tn_c?"\\.0-9\u00b7\u0300-\u036f\u203f-\u2040-":"\\.0-9-"),tn_va="["+tn_ta+"]["+tn_ua+"]*",tn_wa="&"+tn_va+";",tn_xa=tn_wa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ya='"(([^<&"]|'+tn_xa+")*)\"|'(([^<&']|"+tn_xa+")*)'",tn_za="("+tn_va+")([ \t\r\n]+)?=([ \t\r\n]+)?("+
tn_ya+")",tn_Aa=tn_ma+tn_ka+"\\._"+tn_ja+tn_la+"-",tn_Ba="["+tn_ma+"_]["+tn_Aa+"]*";function tn_d(a){a||tn_e("Assertion failed")}function tn_f(a,b){var c=a.indexOf(b);if(-1==c)return[a];var d=[];for(d.push(a.substr(0,c));-1!=c;){var e=a.indexOf(b,c+1);-1!=e?d.push(a.substr(c+1,e-c-1)):d.push(a.substr(c+1));c=e}return d}
function tn_Ca(a,b){if(3==b.nodeType)return a.createTextNode(b.nodeValue);if(4==b.nodeType)return a.createCDATASection(b.nodeValue);if(1==b.nodeType){for(var c=a.createElement(b.nodeName),d=0;d<b.attributes.length;++d){var e=b.attributes[d],f=e.nodeName,e=e.nodeValue;c.setAttribute(f,e)}for(d=b.firstChild;d;d=d.nextSibling)f=arguments.callee(a,d),c.appendChild(f);return c}return a.createComment(b.nodeName)}function tn_g(){this.keys=[]}tn_g.prototype.size=function(){return this.keys.length};
tn_g.prototype.add=function(a,b){var c=b||1;this.contains(a)||(this[":"+a]=c,this.keys.push(a))};tn_g.prototype.remove=function(a){this.contains(a)&&(delete this[":"+a],tn_Da(this.keys,a,!0))};tn_g.prototype.contains=function(a){return"undefined"!=typeof this[":"+a]};tn_g.prototype.map=function(a){for(var b=0;b<this.keys.length;++b){var c=this.keys[b];a.call(this,c,this[":"+c])}};tn_g.prototype.clear=function(){for(var a=0;a<this.keys.length;++a)delete this[":"+this.keys[a]];this.keys.length=0};
function tn_Ea(a,b){for(var c=0;c<a.length;++c)b.call(this,a[c],c)}function tn_Fa(a,b){for(var c=[],d=0;d<a.length;++d)c.push(b(a[d]));return c}function tn_Ga(a){for(var b=0;b<a.length/2;++b){var c=a[b],d=a.length-b-1;a[b]=a[d];a[d]=c}}function tn_Da(a,b,c){for(var d=0,e=0;e<a.length;++e)if(a[e]===b||c&&a[e]==b)a.splice(e--,1),d++;return d}function tn_Ha(a,b){for(var c=0;c<b.length;++c)a.push(b[c])}
function tn_h(a){if(!a)return"";var b="";if(3==a.nodeType||4==a.nodeType||2==a.nodeType)b+=a.nodeValue;else if(1==a.nodeType||9==a.nodeType||11==a.nodeType)for(var c=0;c<a.childNodes.length;++c)b+=arguments.callee(a.childNodes[c]);return b}function tn_Ia(a,b){var c=[];tn_Ja(a,c,b);return c.join("")}
function tn_Ja(a,b,c){if(3==a.nodeType)b.push(tn_Ka(a.nodeValue));else if(4==a.nodeType)c?b.push(a.nodeValue):b.push("<![CDATA["+a.nodeValue+"]]\x3e");else if(8==a.nodeType)b.push("\x3c!--"+a.nodeValue+"--\x3e");else if(1==a.nodeType){b.push("<"+tn_La(a));for(var d=0;d<a.attributes.length;++d){var e=a.attributes[d];e&&e.nodeName&&e.nodeValue&&b.push(" "+tn_La(e)+'="'+tn_Ka(e.nodeValue).replace(/\"/g,"&quot;")+'"')}if(0==a.childNodes.length)b.push("/>");else{b.push(">");for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],
b,c);b.push("</"+tn_La(a)+">")}}else if(9==a.nodeType||11==a.nodeType)for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],b,c)}function tn_La(a){return a.prefix&&0!=a.nodeName.indexOf(a.prefix+":")?a.prefix+":"+a.nodeName:a.nodeName}function tn_Ka(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function tn_Ma(a,b,c){return a.setAttribute(b,c)}function tn_Na(a,b){return a.appendChild(b)}function tn_Oa(a,b){return a.createTextNode(b)}
function tn_e(a){if("undefined"!=typeof Error)throw Error(a||"Assertion Failed");throw a;};function tn_Pa(a){a=tn_f(a,"&");for(var b=a[0],c=1;c<a.length;++c){var d=a[c].indexOf(";");if(-1==d)b+=a[c];else{var e=a[c].substring(0,d),d=a[c].substring(d+1);switch(e){case "lt":e="<";break;case "gt":e=">";break;case "amp":e="&";break;case "quot":e='"';break;case "apos":e="'";break;case "nbsp":e=String.fromCharCode(160);break;default:var f=window.document.createElement("span");f.innerHTML="&"+e+"; ";e=f.childNodes[0].nodeValue.charAt(0)}b+=e+d}}return b}
var tn_Qa=RegExp("^("+tn_oa+")"),tn_Ra=RegExp(tn_sa,"g"),tn_Sa=RegExp("^("+tn_va+")"),tn_Ta=RegExp(tn_za,"g");
function tn_Ua(a){var b=/\/$/,c,d;a.match(/^<\?xml/)?5==a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.0"|'1\.0')/)?(c=tn_Qa,d=tn_Ra):5==a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.1"|'1\.1')/)?(c=tn_Sa,d=tn_Ta):alert("VersionInfo is missing, or unknown version number."):(c=tn_Qa,d=tn_Ra);var e=new tn_i,f=e,h=[],p=f;h.push(p);var m="";a=tn_f(a,"<");for(var l=1;l<a.length;++l){var g=tn_f(a[l],">"),k=g[0],g=tn_Pa(g[1]||"");if(m)if(k=a[l].indexOf(m),-1!=k){var q=a[l].substring(0,
k);p.nodeValue+="<"+q;h.pop();p=h[h.length-1];g=a[l].substring(k+m.length);m=""}else p.nodeValue+="<"+a[l],g=null;else if(0==k.indexOf("![CDATA["))if(q=8,k=a[l].indexOf("]]\x3e"),-1!=k){var q=a[l].substring(q,k),n=e.createCDATASection(q);p.appendChild(n)}else q=a[l].substring(q),g=null,n=e.createCDATASection(q),p.appendChild(n),p=n,h.push(n),m="]]\x3e";else if(0==k.indexOf("!--"))q=3,k=a[l].indexOf("--\x3e"),-1!=k?(q=a[l].substring(q,k),n=e.createComment(q),p.appendChild(n)):(q=a[l].substring(q),
g=null,n=e.createComment(q),p.appendChild(n),p=n,h.push(n),m="--\x3e");else if("/"==k.charAt(0))h.pop(),p=h[h.length-1];else if("?"!=k.charAt(0)&&"!"!=k.charAt(0)){for(var q=k.match(b),n=c.exec(k)[1],n=e.createElement(n),s;s=d.exec(k);){var r=tn_Pa(s[5]||s[7]||"");n.setAttribute(s[1],r)}p.appendChild(n);q||(p=n,h.push(n))}g&&p!=f&&tn_Na(p,e.createTextNode(g))}return f}
function tn_Va(a,b,c){var d;if(b&&(d=b.call(null,a),"boolean"==typeof d&&!d))return!1;for(var e=a.firstChild;e;e=e.nextSibling)if(1==e.nodeType&&(d=arguments.callee.call(this,e,b,c),"boolean"==typeof d&&!d))return!1;if(c&&(d=c.call(null,a),"boolean"==typeof d&&!d))return!1}function tn_j(a,b,c,d){this.attributes=[];this.childNodes=[];tn_j.init.call(this,a,b,c,d)}
tn_j.init=function(a,b,c,d){this.nodeType=a-0;this.nodeName=""+b;this.nodeValue=""+c;this.ownerDocument=d;this.parentNode=this.previousSibling=this.nextSibling=this.lastChild=this.firstChild=null};tn_j.ia=[];
tn_j.recycle=function(a){if(a)if(a.constructor==tn_i)tn_j.recycle(a.documentElement);else if(a.constructor==this){tn_j.ia.push(a);for(var b=0;b<a.attributes.length;++b)tn_j.recycle(a.attributes[b]);for(b=0;b<a.childNodes.length;++b)tn_j.recycle(a.childNodes[b]);a.attributes.length=0;a.childNodes.length=0;tn_j.init.call(a,0,"","",null)}};tn_j.create=function(a,b,c,d){if(0<tn_j.ia.length){var e=tn_j.ia.pop();tn_j.init.call(e,a,b,c,d);return e}return new tn_j(a,b,c,d)};
tn_j.prototype.appendChild=function(a){0==this.childNodes.length&&(this.firstChild=a);a.previousSibling=this.lastChild;a.nextSibling=null;this.lastChild&&(this.lastChild.nextSibling=a);a.parentNode=this;this.lastChild=a;this.childNodes.push(a)};
tn_j.prototype.replaceChild=function(a,b){if(b!=a)for(var c=0;c<this.childNodes.length;++c)if(this.childNodes[c]==b){this.childNodes[c]=a;c=b.parentNode;b.parentNode=null;a.parentNode=c;c=b.previousSibling;b.previousSibling=null;a.previousSibling=c;a.previousSibling&&(a.previousSibling.nextSibling=a);c=b.nextSibling;b.nextSibling=null;a.nextSibling=c;a.nextSibling&&(a.nextSibling.previousSibling=a);this.firstChild==b&&(this.firstChild=a);this.lastChild==b&&(this.lastChild=a);break}};
tn_j.prototype.insertBefore=function(a,b){if(b!=a&&b.parentNode==this){a.parentNode&&a.parentNode.removeChild(a);for(var c=[],d=0;d<this.childNodes.length;++d){var e=this.childNodes[d];e==b&&(c.push(a),a.parentNode=this,a.previousSibling=b.previousSibling,b.previousSibling=a,a.previousSibling&&(a.previousSibling.nextSibling=a),a.nextSibling=b,this.firstChild==b&&(this.firstChild=a));c.push(e)}this.childNodes=c}};
tn_j.prototype.removeChild=function(a){for(var b=[],c=0;c<this.childNodes.length;++c){var d=this.childNodes[c];d!=a?b.push(d):(d.previousSibling&&(d.previousSibling.nextSibling=d.nextSibling),d.nextSibling&&(d.nextSibling.previousSibling=d.previousSibling),this.firstChild==d&&(this.firstChild=d.nextSibling),this.lastChild==d&&(this.lastChild=d.previousSibling))}this.childNodes=b};tn_j.prototype.hasAttributes=function(){return 0<this.attributes.length};
tn_j.prototype.setAttribute=function(a,b){for(var c=0;c<this.attributes.length;++c)if(this.attributes[c].nodeName==a){this.attributes[c].nodeValue=""+b;return}this.attributes.push(tn_j.create(2,a,b,this))};tn_j.prototype.getAttribute=function(a){for(var b=0;b<this.attributes.length;++b)if(this.attributes[b].nodeName==a)return this.attributes[b].nodeValue;return null};
tn_j.prototype.removeAttribute=function(a){for(var b=[],c=0;c<this.attributes.length;++c)this.attributes[c].nodeName!=a&&b.push(this.attributes[c]);this.attributes=b};tn_j.prototype.getElementsByTagName=function(a){var b=[];tn_Va(this,function(c){c.nodeName==a&&b.push(c)},null);return b};tn_j.prototype.getElementById=function(a){var b=null;tn_Va(this,function(c){if(c.getAttribute("id")==a)return b=c,!1},null);return b};
function tn_i(){tn_j.call(this,9,"#document",null,null);this.documentElement=null}tn_i.prototype=new tn_j(9,"#document");tn_i.prototype.clear=function(){tn_j.recycle(this.documentElement);this.documentElement=null};tn_i.prototype.appendChild=function(a){tn_j.prototype.appendChild.call(this,a);this.documentElement=this.childNodes[0]};tn_i.prototype.createElement=function(a){return tn_j.create(1,a,null,this)};
tn_i.prototype.createDocumentFragment=function(){return tn_j.create(11,"#document-fragment",null,this)};tn_i.prototype.createTextNode=function(a){return tn_j.create(3,"#text",a,this)};tn_i.prototype.createAttribute=function(a){return tn_j.create(2,a,null,this)};tn_i.prototype.createComment=function(a){return tn_j.create(8,"#comment",a,this)};tn_i.prototype.createCDATASection=function(a){return tn_j.create(4,"#cdata-section",a,this)};function tn_Wa(a,b){tn_Xa(new tn_k(a,b),b)}
function tn_Xa(a,b){var c=b.getAttribute("select");if(c)b.removeAttribute("select"),tn_Ya(a,b,c);else{if(c=b.getAttribute("display"))if(tn_Za(c,a).d())b.removeAttribute("display");else{b.parentNode.removeChild(b);return}if(c=b.getAttribute("values"))b.removeAttribute("values"),tn__a(a,b,c);if(c=b.getAttribute("transclude"))(c=tn_0a(c,b.ownerDocument))?(b.parentNode.replaceChild(c,b),tn_Xa(a,c)):b.parentNode.removeChild(b),tn_j.recycle(b);else if(c=b.getAttribute("content"))b.removeAttribute("content"),tn_1a(a,
b,c);else{for(var c=[],d=0;d<b.childNodes.length;++d)1==b.childNodes[d].nodeType&&c.push(b.childNodes[d]);for(d=0;d<c.length;++d)tn_Xa(a,c[d])}}}
function tn_Ya(a,b,c){var d=c.split(/;/),e=tn_Za(d[0],a).c();if(0<e.length){c=[];for(var f=1;f<e.length;++f){var h=tn_Ca(b.ownerDocument,b);c.push(h);b.parentNode.insertBefore(h,b)}c.push(b);b=[];for(f=1;f<d.length;++f){var p=d[f],m=0;"#"==p.charAt(m)?(h="number",m++):h="text";"-"==p.charAt(m)?(p="descending",m++):p="ascending";m=tn_2a(d[f].substr(m));b.push({expr:m,type:h,order:p})}a=a.clone(e[0],0,e);tn_3a(a,b);for(f=0;f<a.v();++f)1==a.nodelist[f].nodeType&&tn_Xa(a.clone(a.nodelist[f],f),c[f])}else b.parentNode.removeChild(b)}
function tn__a(a,b,c){c=c.split(/;/);for(var d=0;d<c.length;++d){var e=c[d].indexOf(":");if(!(0>e)){var f=c[d].substr(0,e),e=tn_Za(c[d].substr(e+1),a);"$"==f.charAt(0)?a.fa(f.substr(1),e):f&&tn_Ma(b,f,e.a())}}}
function tn_1a(a,b,c){for(;b.firstChild;)b.removeChild(b.firstChild);a=tn_Za(c,a);if("node-set"==a.type)for(c=0;c<a.value.length;++c){var d=a.value[c];if(1==d.nodeType)for(d=d.firstChild;d;d=d.nextSibling){var e=tn_Ca(b.ownerDocument,d);b.appendChild(e)}else 2==d.nodeType&&(d=b.ownerDocument.createTextNode(d.nodeValue),b.appendChild(d))}else d=tn_Oa(b.ownerDocument,a.a()),b.appendChild(d)}function tn_Za(a,b){var c=tn_2a(a);return c=c.evaluate(b)}
function tn_0a(a,b){var c=b.getElementById(a);return c?c=tn_Ca(b,c):null};function tn_2a(a){tn_4a();var b=tn_5a[a];if(b)return b;if(a.match(/^(\$|@)?\w+$/i))return b=tn_6a(a),tn_5a[a]=b;if(a.match(/^\w+(\/\w+)*$/i))return b=tn_7a(a),tn_5a[a]=b;for(var b=a,c=[],d=null,e=null,f=!1,h=0,p=0,m=0;!f;){h++;a=a.replace(/^\s*/,"");for(var e=d,l=d=null,g="",k=0;k<tn_8a.length;++k){var q=tn_8a[k].re.exec(a);p++;if(q&&0<q.length&&q[0].length>g.length){l=tn_8a[k];g=q[0];break}}!l||l!=tn_9a&&l!=tn_$a&&l!=tn_ab&&l!=tn_bb||e&&e.tag!=tn_cb&&e.tag!=tn_l&&e.tag!=tn_m&&e.tag!=tn_db&&e.tag!=
tn_eb||(l=tn_n);l?(a=a.substr(g.length),d={tag:l,match:g,prec:l.prec?l.prec:0,expr:new tn_fb(g)}):f=!0;for(;tn_gb(c,d);)m++}1!=c.length&&tn_e("XPath parse error "+b+":\n"+tn_hb(c));q=c[0].expr;return tn_5a[b]=q}var tn_5a={};
function tn_gb(a,b){var c=null;if(0<a.length){var d=a[a.length-1];if(d=tn_o[d.tag.key])for(var e=0;e<d.length;++e){var f=d[e],h=tn_ib(a,f[1]);if(h.length){c={tag:f[0],rule:f,match:h};c.prec=tn_jb(c);break}}}if(c&&(!b||c.prec>b.prec||b.tag.left&&c.prec>=b.prec)){for(e=0;e<c.match.matchlength;++e)a.pop();d=tn_Fa(c.match,function(a){return a.expr});c.expr=c.rule[3].apply(null,d);a.push(c);c=!0}else b&&a.push(b),c=!1;return c}
function tn_ib(a,b){for(var c=a.length,d=b.length,e=[],f=e.matchlength=0,d=d-1,c=c-1;0<=d&&0<=c;--d,c-=f){var f=0,h=[];if(b[d]==tn_kb)for(d-=1,e.push(h);0<=c-f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else if(b[d]==tn_lb)for(d-=1,e.push(h);0<=c-f&&2>f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else if(b[d]==tn_mb)if(d-=1,e.push(h),a[c].tag==b[d])for(;0<=c-f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else return[];else if(a[c].tag==b[d])e.push(a[c]),f+=1,e.matchlength+=
1;else return[];tn_Ga(h);h.expr=tn_Fa(h,function(a){return a.expr})}tn_Ga(e);return-1==d?e:[]}function tn_jb(a){var b=0;if(a.rule)if(3<=a.rule.length&&0<=a.rule[2])b=a.rule[2];else for(var c=0;c<a.rule[1].length;++c)var d=a.rule[1][c].prec||2,b=Math.max(b,d);else if(a.tag)b=a.tag.prec||2;else if(a.length)for(c=0;c<a.length;++c)d=tn_jb(a[c]),b=Math.max(b,d);return b}function tn_hb(a){for(var b="",c=0;c<a.length;++c)b&&(b+="\n"),b+=a[c].tag.label;return b}
function tn_k(a,b,c,d,e){this.node=a;this.stylesheet=b||null;this.position=c||0;this.nodelist=d||[a];this.variables={};this.parent=e||null;this.root=e?e.root:9==this.node.nodeType?a:a.ownerDocument}tn_k.prototype.clone=function(a,b,c){return new tn_k(a||this.node,this.stylesheet,"undefined"!=typeof b?b:this.position,c||this.nodelist,this)};tn_k.prototype.fa=function(a,b){this.variables[a]=b};
tn_k.prototype.G=function(a){return"undefined"!=typeof this.variables[a]?this.variables[a]:this.parent?this.parent.G(a):null};tn_k.prototype.Na=function(a){this.node=this.nodelist[a];this.position=a};tn_k.prototype.v=function(){return this.nodelist.length};function tn_p(a){this.value=a;this.type="string"}tn_p.prototype.a=function(){return this.value};tn_p.prototype.d=function(){return 0<this.value.length};tn_p.prototype.b=function(){return this.value-0};tn_p.prototype.c=function(){tn_e(this)};
function tn_q(a){this.value=a;this.type="boolean"}tn_q.prototype.a=function(){return""+this.value};tn_q.prototype.d=function(){return this.value};tn_q.prototype.b=function(){return this.value?1:0};tn_q.prototype.c=function(){tn_e(this)};function tn_r(a){this.value=a;this.type="number"}tn_r.prototype.a=function(){return""+this.value};tn_r.prototype.d=function(){return!!this.value};tn_r.prototype.b=function(){return this.value-0};tn_r.prototype.c=function(){tn_e(this)};
function tn_s(a){this.value=a;this.type="node-set"}tn_s.prototype.a=function(){return 0==this.value.length?"":tn_h(this.value[0])};tn_s.prototype.d=function(){return 0<this.value.length};tn_s.prototype.b=function(){return this.a()-0};tn_s.prototype.c=function(){return this.value};function tn_fb(a){this.value=a}tn_fb.prototype.evaluate=function(){return new tn_p(this.value)};function tn_t(){this.absolute=!1;this.rootExpr=null;this.steps=[]}tn_t.prototype.k=function(a){this.steps.push(a)};
tn_t.prototype.ca=function(a){this.steps.unshift(a)};tn_t.prototype.evaluate=function(a){var b;b=this.rootExpr?this.rootExpr.evaluate(a).c():this.absolute?[a.root]:[a.node];for(var c=[],d=0;d<b.length;++d){var e=b[d];tn_nb(c,this.steps,0,e,a)}return new tn_s(c)};function tn_nb(a,b,c,d,e){var f=b[c];d=e.clone(d);f=f.evaluate(d).c();for(d=0;d<f.length;++d)c==b.length-1?a.push(f[d]):tn_nb(a,b,c+1,f[d],e)}function tn_u(a,b,c){this.axis=a;this.nodetest=b;this.predicate=c||[]}tn_u.prototype.la=function(a){this.predicate.push(a)};
tn_u.prototype.evaluate=function(a){var b=a.node,c=[];if(this.axis==tn_v.ANCESTOR_OR_SELF)for(c.push(b),b=b.parentNode;b;b=b.parentNode)c.push(b);else if(this.axis==tn_v.ANCESTOR)for(b=b.parentNode;b;b=b.parentNode)c.push(b);else if(this.axis==tn_v.ATTRIBUTE)tn_Ha(c,b.attributes);else if(this.axis==tn_v.CHILD)tn_Ha(c,b.childNodes);else if(this.axis==tn_v.DESCENDANT_OR_SELF)c.push(b),tn_ob(c,b);else if(this.axis==tn_v.DESCENDANT)tn_ob(c,b);else if(this.axis==tn_v.FOLLOWING)for(;b;b=b.parentNode)for(var d=
b.nextSibling;d;d=d.nextSibling)c.push(d),tn_ob(c,d);else if(this.axis==tn_v.FOLLOWING_SIBLING)for(b=b.nextSibling;b;b=b.nextSibling)c.push(b);else if(this.axis==tn_v.NAMESPACE)tn_e("not implemented: axis namespace");else if(this.axis==tn_v.PARENT)b.parentNode&&c.push(b.parentNode);else if(this.axis==tn_v.PRECEDING)for(;b;b=b.parentNode)for(d=b.previousSibling;d;d=d.previousSibling)c.push(d),tn_pb(c,d);else if(this.axis==tn_v.PRECEDING_SIBLING)for(b=b.previousSibling;b;b=b.previousSibling)c.push(b);
else this.axis==tn_v.SELF?c.push(b):tn_e("ERROR -- NO SUCH AXIS: "+this.axis);for(var d=c,c=[],e=0;e<d.length;++e)b=d[e],this.nodetest.evaluate(a.clone(b,e,d)).d()&&c.push(b);for(e=0;e<this.predicate.length;++e)for(var d=c,c=[],f=0;f<d.length;++f)b=d[f],this.predicate[e].evaluate(a.clone(b,f,d)).d()&&c.push(b);return new tn_s(c)};function tn_qb(){this.value=new tn_q(!0)}tn_qb.prototype.evaluate=function(){return this.value};function tn_rb(){}
tn_rb.prototype.evaluate=function(a){return new tn_q(1==a.node.nodeType||2==a.node.nodeType)};function tn_sb(){}tn_sb.prototype.evaluate=function(a){return new tn_q(3==a.node.nodeType)};function tn_tb(){}tn_tb.prototype.evaluate=function(a){return new tn_q(8==a.node.nodeType)};function tn_ub(a){this.target=a}tn_ub.prototype.evaluate=function(a){return new tn_q(7==a.node.nodeType&&(!this.target||a.node.nodeName==this.target))};function tn_vb(a){this.regex=RegExp("^"+a+":");this.nsprefix=a}
tn_vb.prototype.evaluate=function(a){a=a.node;return new tn_q(this.regex.test(a.nodeName))};function tn_wb(a){this.name=a}tn_wb.prototype.evaluate=function(a){a=a.node;return new tn_q(a.nodeName==this.name)};function tn_xb(a){this.expr=a}tn_xb.prototype.evaluate=function(a){var b=this.expr.evaluate(a);return"number"==b.type?new tn_q(a.position==b.b()-1):new tn_q(b.d())};function tn_yb(a){this.name=a;this.args=[]}tn_yb.prototype.S=function(a){this.args.push(a)};
tn_yb.prototype.evaluate=function(a){var b=""+this.name.value;return(b=this.xpathfunctions[b])?b.call(this,a):new tn_q(!1)};
tn_yb.prototype.xpathfunctions={last:function(a){tn_d(0==this.args.length);return new tn_r(a.v())},position:function(a){tn_d(0==this.args.length);return new tn_r(a.position+1)},count:function(a){tn_d(1==this.args.length);a=this.args[0].evaluate(a);return new tn_r(a.c().length)},id:function(a){tn_d(1==this.args.length);var b=this.args[0].evaluate(a),c=[],d;if("node-set"==b.type){d=[];for(var e=b.c(),b=0;b<e.length;++b)for(var f=tn_h(e[b]).split(/\s+/),h=0;h<f.length;++h)d.push(f[h])}else d=b.a().split(/\s+/);
a=a.node.ownerDocument;for(b=0;b<d.length;++b)(e=a.getElementById(d[b]))&&c.push(e);return new tn_s(c)},"local-name":function(){tn_e("not implmented yet: XPath function local-name()")},"namespace-uri":function(){tn_e("not implmented yet: XPath function namespace-uri()")},name:function(a){tn_d(1==this.args.length||0==this.args.length);a=0==this.args.length?[a.node]:this.args[0].evaluate(a).c();return 0==a.length?new tn_p(""):new tn_p(a[0].nodeName)},string:function(a){tn_d(1==this.args.length||0==
this.args.length);return 0==this.args.length?new tn_p((new tn_s([a.node])).a()):new tn_p(this.args[0].evaluate(a).a())},concat:function(a){for(var b="",c=0;c<this.args.length;++c)b+=this.args[c].evaluate(a).a();return new tn_p(b)},document:function(a){var b=this.args[0].evaluate(a).a();if(""===b&&a.stylesheet)return new tn_s([a.stylesheet]);tn_e("Can't resolve uri in document(\""+b+'")')},"starts-with":function(a){tn_d(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();
return new tn_q(0==b.indexOf(a))},contains:function(a){tn_d(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();return new tn_q(-1!=b.indexOf(a))},"substring-before":function(a){tn_d(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();a=b.indexOf(a);b=-1==a?"":b.substr(0,a);return new tn_p(b)},"substring-after":function(a){tn_d(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();var c=b.indexOf(a),
b=-1==c?"":b.substr(c+a.length);return new tn_p(b)},substring:function(a){tn_d(2==this.args.length||3==this.args.length);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).b();if(2==this.args.length)c=Math.max(0,Math.round(c)-1),b=b.substr(c);else{a=this.args[2].evaluate(a).b();var d=Math.round(c)-1,c=Math.max(0,d);a=Math.round(a)-Math.max(0,-d);b=b.substr(c,a)}return new tn_p(b)},"string-length":function(a){a=0<this.args.length?this.args[0].evaluate(a).a():(new tn_s([a.node])).a();return new tn_r(a.length)},
"normalize-space":function(a){a=0<this.args.length?this.args[0].evaluate(a).a():(new tn_s([a.node])).a();a=a.replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g," ");return new tn_p(a)},translate:function(a){tn_d(3==this.args.length);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a();a=this.args[2].evaluate(a).a();for(var d=0;d<c.length;++d)b=b.replace(RegExp(c.charAt(d),"g"),a.charAt(d));return new tn_p(b)},"boolean":function(a){tn_d(1==this.args.length);return new tn_q(this.args[0].evaluate(a).d())},
not:function(a){tn_d(1==this.args.length);a=!this.args[0].evaluate(a).d();return new tn_q(a)},"true":function(){tn_d(0==this.args.length);return new tn_q(!0)},"false":function(){tn_d(0==this.args.length);return new tn_q(!1)},lang:function(a){tn_d(1==this.args.length);var b=this.args[0].evaluate(a).a(),c;for(a=a.node;a&&a!=a.parentNode&&!(c=a.getAttribute("xml:lang"));)a=a.parentNode;return c?(b=RegExp("^"+b+"$","i"),new tn_q(b.test(c)||b.test(c.replace(/_.*$/,"")))):new tn_q(!1)},number:function(a){tn_d(1==
this.args.length||0==this.args.length);return 1==this.args.length?new tn_r(this.args[0].evaluate(a).b()):new tn_r((new tn_s([a.node])).b())},sum:function(a){tn_d(1==this.args.length);a=this.args[0].evaluate(a).c();for(var b=0,c=0;c<a.length;++c)b+=tn_h(a[c])-0;return new tn_r(b)},floor:function(a){tn_d(1==this.args.length);a=this.args[0].evaluate(a).b();return new tn_r(Math.floor(a))},ceiling:function(a){tn_d(1==this.args.length);a=this.args[0].evaluate(a).b();return new tn_r(Math.ceil(a))},round:function(a){tn_d(1==
this.args.length);a=this.args[0].evaluate(a).b();return new tn_r(Math.round(a))},"ext-join":function(a){tn_d(2==this.args.length);var b=this.args[0].evaluate(a).c();a=this.args[1].evaluate(a).a();for(var c="",d=0;d<b.length;++d)c&&(c+=a),c+=tn_h(b[d]);return new tn_p(c)},"ext-if":function(a){tn_d(3==this.args.length);return this.args[0].evaluate(a).d()?this.args[1].evaluate(a):this.args[2].evaluate(a)},"ext-cardinal":function(a){tn_d(1<=this.args.length);for(var b=this.args[0].evaluate(a).b(),c=[],
d=0;d<b;++d)c.push(a.node);return new tn_s(c)}};function tn_zb(a,b){this.expr1=a;this.expr2=b}tn_zb.prototype.evaluate=function(a){var b=this.expr1.evaluate(a).c();a=this.expr2.evaluate(a).c();for(var c=b.length,d=0;d<a.length;++d){for(var e=a[d],f=!1,h=0;h<c;++h)b[h]==e&&(f=!0,h=c);f||b.push(e)}return new tn_s(b)};function tn_Ab(a,b){this.filter=a;this.rel=b}
tn_Ab.prototype.evaluate=function(a){for(var b=this.filter.evaluate(a).c(),c=[],d=0;d<b.length;++d)for(var e=this.rel.evaluate(a.clone(b[d],d,b)).c(),f=0;f<e.length;++f)c.push(e[f]);return new tn_s(c)};function tn_Bb(a,b){this.expr=a;this.predicate=b}tn_Bb.prototype.evaluate=function(a){for(var b=this.expr.evaluate(a).c(),c=0;c<this.predicate.length;++c)for(var d=b,b=[],e=0;e<d.length;++e){var f=d[e];this.predicate[c].evaluate(a.clone(f,e,d)).d()&&b.push(f)}return new tn_s(b)};
function tn_Cb(a){this.expr=a}tn_Cb.prototype.evaluate=function(a){return new tn_r(-this.expr.evaluate(a).b())};function tn_Db(a,b,c){this.expr1=a;this.expr2=c;this.op=b}
tn_Db.prototype.evaluate=function(a){var b;switch(this.op.value){case "or":b=new tn_q(this.expr1.evaluate(a).d()||this.expr2.evaluate(a).d());break;case "and":b=new tn_q(this.expr1.evaluate(a).d()&&this.expr2.evaluate(a).d());break;case "+":b=new tn_r(this.expr1.evaluate(a).b()+this.expr2.evaluate(a).b());break;case "-":b=new tn_r(this.expr1.evaluate(a).b()-this.expr2.evaluate(a).b());break;case "*":b=new tn_r(this.expr1.evaluate(a).b()*this.expr2.evaluate(a).b());break;case "mod":b=new tn_r(this.expr1.evaluate(a).b()%
this.expr2.evaluate(a).b());break;case "div":b=new tn_r(this.expr1.evaluate(a).b()/this.expr2.evaluate(a).b());break;case "=":b=this.compare(a,function(a,b){return a==b});break;case "!=":b=this.compare(a,function(a,b){return a!=b});break;case "<":b=this.compare(a,function(a,b){return a<b});break;case "<=":b=this.compare(a,function(a,b){return a<=b});break;case ">":b=this.compare(a,function(a,b){return a>b});break;case ">=":b=this.compare(a,function(a,b){return a>=b});break;default:tn_e("BinaryExpr.evaluate: "+
this.op.value)}return b};
tn_Db.prototype.compare=function(a,b){var c=this.expr1.evaluate(a),d=this.expr2.evaluate(a);if("node-set"==c.type&&"node-set"==d.type)for(var c=c.c(),e=d.c(),d=!1,f=0;f<c.length;++f)for(var h=0;h<e.length;++h)b(tn_h(c[f]),tn_h(e[h]))&&(d=!0,h=e.length,f=c.length);else if("node-set"==c.type||"node-set"==d.type)if("number"==c.type)for(c=c.b(),e=d.c(),d=!1,f=0;f<e.length;++f){if(h=tn_h(e[f])-0,b(c,h)){d=!0;break}}else if("number"==d.type)for(e=c.c(),c=d.b(),d=!1,f=0;f<e.length;++f){if(h=tn_h(e[f])-0,
b(h,c)){d=!0;break}}else if("string"==c.type)for(c=c.a(),e=d.c(),d=!1,f=0;f<e.length;++f){if(h=tn_h(e[f]),b(c,h)){d=!0;break}}else if("string"==d.type)for(e=c.c(),c=d.a(),d=!1,f=0;f<e.length;++f){if(h=tn_h(e[f]),b(h,c)){d=!0;break}}else d=b(c.d(),d.d());else d="boolean"==c.type||"boolean"==d.type?b(c.d(),d.d()):"number"==c.type||"number"==d.type?b(c.b(),d.b()):b(c.a(),d.a());return new tn_q(!!d)};function tn_Eb(a){this.value=a}tn_Eb.prototype.evaluate=function(){return new tn_p(this.value)};
function tn_Fb(a){this.value=a}tn_Fb.prototype.evaluate=function(){return new tn_r(this.value)};function tn_Gb(a){this.name=a}tn_Gb.prototype.evaluate=function(a){return a.G(this.name)};function tn_w(a){return a}function tn_Hb(a,b){b.absolute=!0;return b}function tn_Ib(a,b){b.absolute=!0;b.ca(tn_x(a.value));return b}function tn_Jb(){var a=new tn_t;a.k(tn_x("."));a.absolute=!0;return a}function tn_Kb(a){var b=new tn_t;b.absolute=!0;b.k(tn_x(a.value));return b}
function tn_Lb(a){var b=new tn_t;b.k(a);return b}function tn_Mb(a,b,c){a.k(c);return a}function tn_Nb(a,b){a.k(tn_x(b.value));return a}function tn_Ob(a,b,c){b=new tn_t;b.rootExpr=a;b.k(c);return b}function tn_Pb(a){return tn_x(a.value)}function tn_Qb(a){return tn_x(a.value)}function tn_Rb(a,b,c){return new tn_u(a.value,c)}function tn_Sb(a,b){return new tn_u("attribute",b)}function tn_Tb(a){return new tn_u("child",a)}function tn_Ub(a,b){a.la(b);return a}
function tn_x(a){switch(a){case "//":return new tn_u("descendant-or-self",new tn_qb);case ".":return new tn_u("self",new tn_qb);case "..":return new tn_u("parent",new tn_qb)}}function tn_Vb(){return new tn_rb}function tn_Wb(a){return new tn_vb(a.value)}function tn_Xb(a){return new tn_wb(a.value)}function tn_Yb(a){a=a.value.replace(/\s*\($/,"");switch(a){case "node":return new tn_qb;case "text":return new tn_sb;case "comment":return new tn_tb;case "processing-instruction":return new tn_ub("")}}
function tn_Zb(a,b){var c=a.replace(/\s*\($/,"");"processing-instruction"!=c&&tn_e(c);return new tn_ub(b.value)}function tn__b(a,b){return new tn_xb(b)}function tn_0b(a,b){return b}function tn_1b(a){return new tn_yb(a)}function tn_2b(a,b,c,d){a=new tn_yb(a);a.S(c);for(c=0;c<d.length;++c)a.S(d[c]);return a}function tn_3b(a,b){return b}function tn_4b(a,b,c){return new tn_zb(a,c)}function tn_5b(a,b,c){return new tn_Ab(a,c)}function tn_6b(a,b,c){c.ca(tn_x(b.value));return new tn_Ab(a,c)}
function tn_7b(a,b){return 0<b.length?new tn_Bb(a,b):a}function tn_8b(a,b){return new tn_Cb(b)}function tn_y(a,b,c){return new tn_Db(a,b,c)}function tn_9b(a){a=a.value.substring(1,a.value.length-1);return new tn_Eb(a)}function tn_$b(a){return new tn_Fb(a.value)}function tn_ac(a,b){return new tn_Gb(b.value)}
function tn_6a(a){if("$"==a.charAt(0))return new tn_Gb(a.substr(1));if("@"==a.charAt(0)){a=new tn_wb(a.substr(1));a=new tn_u("attribute",a);var b=new tn_t;b.k(a);return b}if(a.match(/^[0-9]+$/))return new tn_Fb(a);a=new tn_wb(a);a=new tn_u("child",a);b=new tn_t;b.k(a);return b}function tn_7a(a){a=tn_f(a,"/");for(var b=new tn_t,c=0;c<a.length;++c){var d=new tn_wb(a[c]),d=new tn_u("child",d);b.k(d)}return b}
var tn_v={ANCESTOR_OR_SELF:"ancestor-or-self",ANCESTOR:"ancestor",ATTRIBUTE:"attribute",CHILD:"child",DESCENDANT_OR_SELF:"descendant-or-self",DESCENDANT:"descendant",FOLLOWING_SIBLING:"following-sibling",FOLLOWING:"following",NAMESPACE:"namespace",PARENT:"parent",PRECEDING_SIBLING:"preceding-sibling",PRECEDING:"preceding",SELF:"self"},tn_bc=[tn_v.ANCESTOR_OR_SELF,tn_v.ANCESTOR,tn_v.ATTRIBUTE,tn_v.CHILD,tn_v.DESCENDANT_OR_SELF,tn_v.DESCENDANT,tn_v.FOLLOWING_SIBLING,tn_v.FOLLOWING,tn_v.NAMESPACE,tn_v.PARENT,
tn_v.PRECEDING_SIBLING,tn_v.PRECEDING,tn_v.SELF].join("|"),tn_cc={label:"|",prec:17,re:/^\|/},tn_l={label:"//",prec:19,re:/^\/\//},tn_m={label:"/",prec:30,re:/^\//},tn_db={label:"::",prec:20,re:/^::/},tn_dc={label:":",prec:1E3,re:/^:/},tn_ec={label:"[axis]",re:RegExp("^("+tn_bc+")")},tn_fc={label:"(",prec:34,re:/^\(/},tn_z={label:")",re:/^\)/},tn_gc={label:"..",prec:34,re:/^\.\./},tn_hc={label:".",prec:34,re:/^\./},tn_cb={label:"@",prec:34,re:/^@/},tn_ic={label:",",re:/^,/},tn_bb={label:"or",prec:10,
re:/^or\b/},tn_ab={label:"and",prec:11,re:/^and\b/},tn_jc={label:"=",prec:12,re:/^=/},tn_kc={label:"!=",prec:12,re:/^!=/},tn_lc={label:">=",prec:13,re:/^>=/},tn_mc={label:">",prec:13,re:/^>/},tn_nc={label:"<=",prec:13,re:/^<=/},tn_oc={label:"<",prec:13,re:/^</},tn_pc={label:"+",prec:14,re:/^\+/,left:!0},tn_qc={label:"-",prec:14,re:/^\-/,left:!0},tn_9a={label:"div",prec:15,re:/^div\b/,left:!0},tn_$a={label:"mod",prec:15,re:/^mod\b/,left:!0},tn_rc={label:"[",prec:32,re:/^\[/},tn_sc={label:"]",re:/^\]/},
tn_eb={label:"$",re:/^\$/},tn_tc={label:"[ncname]",re:RegExp("^"+tn_Ba)},tn_uc={label:"*",prec:15,re:/^\*/,left:!0},tn_vc={label:"[litq]",prec:20,re:/^'[^\']*'/},tn_wc={label:"[litqq]",prec:20,re:/^"[^\"]*"/},tn_xc={label:"[number]",prec:35,re:/^\d+(\.\d*)?/},tn_n={label:"[qname]",re:RegExp("^("+tn_Ba+":)?"+tn_Ba)},tn_yc={label:"[nodetest-start]",re:/^(processing-instruction|comment|text|node)\(/},tn_8a=[tn_l,tn_m,tn_gc,tn_hc,tn_db,tn_dc,tn_ec,tn_yc,tn_fc,tn_z,tn_rc,tn_sc,tn_cb,tn_ic,tn_bb,tn_ab,
tn_kc,tn_jc,tn_lc,tn_mc,tn_nc,tn_oc,tn_pc,tn_qc,tn_uc,tn_cc,tn_$a,tn_9a,tn_vc,tn_wc,tn_xc,tn_n,tn_tc,tn_eb],tn_zc={label:"LocationPath"},tn_A={label:"RelativeLocationPath"},tn_Ac={label:"AbsoluteLocationPath"},tn_B={label:"Step"},tn_C={label:"NodeTest"},tn_Bc={label:"Predicate"},tn_Cc={label:"Literal"},tn_D={label:"Expr"},tn_E={label:"PrimaryExpr"},tn_Dc={label:"Variablereference"},tn_Ec={label:"Number"},tn_Fc={label:"FunctionCall"},tn_Gc={label:"ArgumentRemainder"},tn_F={label:"PathExpr"},tn_Hc=
{label:"UnionExpr"},tn_Ic={label:"FilterExpr"},tn_Jc={label:"Digits"},tn_Kc=[tn_zc,tn_A,tn_Ac,tn_B,tn_C,tn_Bc,tn_Cc,tn_D,tn_E,tn_Dc,tn_Ec,tn_Fc,tn_Gc,tn_F,tn_Hc,tn_Ic,tn_Jc],tn_lb={label:"?"},tn_kb={label:"*"},tn_mb={label:"+"},tn_Lc=[[tn_zc,[tn_A],18,tn_w],[tn_zc,[tn_Ac],18,tn_w],[tn_Ac,[tn_m,tn_A],18,tn_Hb],[tn_Ac,[tn_l,tn_A],18,tn_Ib],[tn_Ac,[tn_m],0,tn_Jb],[tn_Ac,[tn_l],0,tn_Kb],[tn_A,[tn_B],31,tn_Lb],[tn_A,[tn_A,tn_m,tn_B],31,tn_Mb],[tn_A,[tn_A,tn_l,tn_B],31,tn_Nb],[tn_A,[tn_E,tn_m,tn_B],31,
tn_Ob],[tn_B,[tn_hc],33,tn_Pb],[tn_B,[tn_gc],33,tn_Qb],[tn_B,[tn_ec,tn_db,tn_C],33,tn_Rb],[tn_B,[tn_cb,tn_C],33,tn_Sb],[tn_B,[tn_C],33,tn_Tb],[tn_B,[tn_B,tn_Bc],33,tn_Ub],[tn_C,[tn_uc],33,tn_Vb],[tn_C,[tn_tc,tn_dc,tn_uc],33,tn_Wb],[tn_C,[tn_n],33,tn_Xb],[tn_C,[tn_yc,tn_z],33,tn_Yb],[tn_C,[tn_yc,tn_Cc,tn_z],33,tn_Zb],[tn_Bc,[tn_rc,tn_D,tn_sc],33,tn__b],[tn_E,[tn_Dc],33,tn_w],[tn_E,[tn_fc,tn_D,tn_z],33,tn_0b],[tn_E,[tn_Cc],30,tn_w],[tn_E,[tn_Ec],30,tn_w],[tn_E,[tn_Fc],30,tn_w],[tn_Fc,[tn_n,tn_fc,tn_z],
-1,tn_1b],[tn_Fc,[tn_n,tn_fc,tn_D,tn_Gc,tn_kb,tn_z],-1,tn_2b],[tn_Gc,[tn_ic,tn_D],-1,tn_3b],[tn_Hc,[tn_F],20,tn_w],[tn_Hc,[tn_Hc,tn_cc,tn_F],20,tn_4b],[tn_F,[tn_zc],20,tn_w],[tn_F,[tn_Ic],19,tn_w],[tn_F,[tn_Ic,tn_m,tn_A],20,tn_5b],[tn_F,[tn_Ic,tn_l,tn_A],20,tn_6b],[tn_Ic,[tn_E,tn_Bc,tn_kb],20,tn_7b],[tn_D,[tn_E],16,tn_w],[tn_D,[tn_Hc],16,tn_w],[tn_D,[tn_qc,tn_D],-1,tn_8b],[tn_D,[tn_D,tn_bb,tn_D],-1,tn_y],[tn_D,[tn_D,tn_ab,tn_D],-1,tn_y],[tn_D,[tn_D,tn_jc,tn_D],-1,tn_y],[tn_D,[tn_D,tn_kc,tn_D],-1,
tn_y],[tn_D,[tn_D,tn_oc,tn_D],-1,tn_y],[tn_D,[tn_D,tn_nc,tn_D],-1,tn_y],[tn_D,[tn_D,tn_mc,tn_D],-1,tn_y],[tn_D,[tn_D,tn_lc,tn_D],-1,tn_y],[tn_D,[tn_D,tn_pc,tn_D],-1,tn_y,!0],[tn_D,[tn_D,tn_qc,tn_D],-1,tn_y,!0],[tn_D,[tn_D,tn_uc,tn_D],-1,tn_y,!0],[tn_D,[tn_D,tn_9a,tn_D],-1,tn_y,!0],[tn_D,[tn_D,tn_$a,tn_D],-1,tn_y,!0],[tn_Cc,[tn_vc],-1,tn_9b],[tn_Cc,[tn_wc],-1,tn_9b],[tn_Ec,[tn_xc],-1,tn_$b],[tn_Dc,[tn_eb,tn_n],200,tn_ac]],tn_o=[];
function tn_4a(){function a(a,b,c){a[b]||(a[b]=[]);a[b].push(c)}if(!tn_o.length){tn_Lc.sort(function(a,b){var c=a[1].length,d=b[1].length;return c<d?1:c>d?-1:0});for(var b=1,c=0;c<tn_Kc.length;++c)tn_Kc[c].key=b++;for(c=0;c<tn_8a.length;++c)tn_8a[c].key=b++;for(c=0;c<tn_Lc.length;++c)for(var b=tn_Lc[c],d=b[1],e=d.length-1;0<=e;--e)if(d[e]==tn_mb){a(tn_o,d[e-1].key,b);break}else if(d[e]==tn_kb||d[e]==tn_lb)a(tn_o,d[e-1].key,b),--e;else{a(tn_o,d[e].key,b);break}tn_Ea(tn_o,function(){})}}
function tn_ob(a,b){for(var c=b.firstChild;c;c=c.nextSibling)a.push(c),arguments.callee(a,c)}function tn_pb(a,b){for(var c=b.lastChild;c;c=c.previousSibling)a.push(c),arguments.callee(a,c)}
function tn_3a(a,b){if(0!=b.length){for(var c=[],d=0;d<a.v();++d){for(var e=a.nodelist[d],f={node:e,key:[]},e=a.clone(e,0,[e]),h=0;h<b.length;++h){var p=b[h],m=p.expr.evaluate(e),l;"text"==p.type?l=m.a():"number"==p.type&&(l=m.b());f.key.push({value:l,order:p.order})}f.key.push({value:d,order:"ascending"});c.push(f)}c.sort(tn_Mc);f=[];for(d=0;d<c.length;++d)f.push(c[d].node);a.nodelist=f;a.Na(0)}}
function tn_Mc(a,b){for(var c=0;c<a.key.length;++c){var d="descending"==a.key[c].order?-1:1;if(a.key[c].value>b.key[c].value)return 1*d;if(a.key[c].value<b.key[c].value)return-1*d}return 0}function tn_G(a,b){var c=tn_2a(a);return c=c.evaluate(b)};function tn_Nc(a,b){var c=(new tn_i).createDocumentFragment();tn_Oc(new tn_k(a,b),b,c);return c=tn_Ia(c)}
function tn_Oc(a,b,c){var d=9==c.nodeType?c:c.ownerDocument,e=b.nodeName.split(/:/);if(1==e.length||"xsl"!=e[0])tn_Pc(a,b,c,d);else switch(e[1]){case "apply-imports":alert("not implemented: "+e[1]);break;case "apply-templates":e=(e=tn_H(b,"select"))?tn_G(e,a).c():a.node.childNodes;a=a.clone(e[0],0,e);tn_Qc(a,b);tn_Rc(a,b);var f=tn_H(b,"mode"),d=b.ownerDocument.documentElement,e=[];for(b=0;b<d.childNodes.length;++b){var h=d.childNodes[b];1==h.nodeType&&"xsl:template"==h.nodeName&&h.getAttribute("mode")==
f&&e.push(h)}for(d=0;d<a.v();++d)for(h=a.nodelist[d],b=0;b<e.length;++b)tn_Oc(a.clone(h,d),e[b],c);break;case "attribute":e=tn_H(b,"name");e=tn_Sc(e,a);h=d.createDocumentFragment();tn_I(a,b,h);b=tn_h(h);c.setAttribute(e,b);break;case "attribute-set":alert("not implemented: "+e[1]);break;case "call-template":e=tn_H(b,"name");d=b.ownerDocument.documentElement;a=a.clone();tn_Qc(a,b);for(b=0;b<d.childNodes.length;++b)if(h=d.childNodes[b],1==h.nodeType&&"xsl:template"==h.nodeName&&h.getAttribute("name")==
e){tn_I(a,h,c);break}break;case "choose":tn_Tc(a,b,c);break;case "comment":h=d.createDocumentFragment();tn_I(a,b,h);b=tn_h(h);b=d.createComment(b);c.appendChild(b);break;case "copy":(h=tn_Uc(c,a.node,d))&&tn_I(a,b,h);break;case "copy-of":e=tn_H(b,"select");b=tn_G(e,a);if("node-set"==b.type)for(e=b.c(),b=0;b<e.length;++b)tn_Vc(c,e[b],d);else h=tn_Oa(d,b.a()),c.appendChild(h);break;case "decimal-format":alert("not implemented: "+e[1]);break;case "element":e=tn_H(b,"name");e=tn_Sc(e,a);h=d.createElement(e);
c.appendChild(h);tn_I(a,b,h);break;case "fallback":alert("not implemented: "+e[1]);break;case "for-each":tn_Wc(a,b,c);break;case "if":d=tn_H(b,"test");d=tn_G(d,a);null!=d&&d.d()&&tn_I(a,b,c);break;case "import":alert("not implemented: "+e[1]);break;case "include":alert("not implemented: "+e[1]);break;case "key":alert("not implemented: "+e[1]);break;case "message":alert("not implemented: "+e[1]);break;case "namespace-alias":alert("not implemented: "+e[1]);break;case "number":alert("not implemented: "+
e[1]);break;case "otherwise":alert("error if here: "+e[1]);break;case "output":break;case "preserve-space":break;case "processing-instruction":alert("not implemented: "+e[1]);break;case "sort":break;case "strip-space":alert("not implemented: "+e[1]);break;case "stylesheet":case "transform":tn_I(a,b,c);break;case "template":(d=tn_H(b,"match"))&&tn_Xc(d,a)&&tn_I(a,b,c);break;case "text":b=tn_h(b);h=d.createTextNode(b);c.appendChild(h);break;case "value-of":e=tn_H(b,"select");b=tn_G(e,a).a();h=d.createTextNode(b);
c.appendChild(h);break;case "param":tn_Yc(a,b,!1);break;case "variable":tn_Yc(a,b,!0);break;case "when":alert("error if here: "+e[1]);break;case "with-param":alert("error if here: "+e[1]);break;default:alert("error if here: "+e[1])}}function tn_Qc(a,b){for(var c=0;c<b.childNodes.length;++c){var d=b.childNodes[c];1==d.nodeType&&"xsl:with-param"==d.nodeName&&tn_Yc(a,d,!0)}}
function tn_Rc(a,b){for(var c=[],d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(1==e.nodeType&&"xsl:sort"==e.nodeName){var f=tn_H(e,"select"),f=tn_2a(f),h=tn_H(e,"data-type")||"text",e=tn_H(e,"order")||"ascending";c.push({expr:f,type:h,order:e})}}tn_3a(a,c)}function tn_Yc(a,b,c){var d=tn_H(b,"name"),e=tn_H(b,"select");0<b.childNodes.length?(e=b.ownerDocument.createDocumentFragment(),tn_I(a,b,e),b=new tn_s([e])):b=e?tn_G(e,a):new tn_p("");!c&&a.G(d)||a.fa(d,b)}
function tn_Tc(a,b,c){for(var d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(1==e.nodeType)if("xsl:when"==e.nodeName){var f=tn_H(e,"test");if(tn_G(f,a).d()){tn_I(a,e,c);break}}else if("xsl:otherwise"==e.nodeName){tn_I(a,e,c);break}}}function tn_Wc(a,b,c){var d=tn_H(b,"select"),d=tn_G(d,a).c();a=a.clone(d[0],0,d);tn_Rc(a,b);for(d=0;d<a.v();++d){var e=a.nodelist[d];tn_I(a.clone(e,d),b,c)}}function tn_I(a,b,c){a=a.clone();for(var d=0;d<b.childNodes.length;++d)tn_Oc(a,b.childNodes[d],c)}
function tn_Pc(a,b,c,d){if(3==b.nodeType)tn_Zc(b)&&(d=d.createTextNode(b.nodeValue),c.appendChild(d));else if(1==b.nodeType){d=d.createElement(b.nodeName);for(var e=0;e<b.attributes.length;++e){var f=b.attributes[e];if(f){var h=f.nodeName,f=tn_Sc(f.nodeValue,a);d.setAttribute(h,f)}}c.appendChild(d);tn_I(a,b,d)}else tn_I(a,b,c)}
function tn_Zc(a){if(!a.nodeValue.match(/^\s*$/))return!0;a=a.parentNode;if("xsl:text"==a.nodeName)return!0;for(;a&&1==a.nodeType;){var b=a.getAttribute("xml:space");if(b)if("default"==b)break;else if("preserve"==b)return!0;a=a.parentNode}return!1}function tn_Sc(a,b){var c=tn_f(a,"{");if(1==c.length)return a;for(var d="",e=0;e<c.length;++e){var f=tn_f(c[e],"}");if(2!=f.length)d+=c[e];else var h=tn_G(f[0],b).a(),d=d+(h+f[1])}return d}function tn_H(a,b){var c=a.getAttribute(b);return c?tn_Pa(c):c}
function tn_Vc(a,b,c){if(11==b.nodeType||9==b.nodeType)for(var d=0;d<b.childNodes.length;++d)arguments.callee(a,b.childNodes[d],c);else{var e=tn_Uc(a,b,c);if(e){for(d=0;d<b.attributes.length;++d)arguments.callee(e,b.attributes[d],c);for(d=0;d<b.childNodes.length;++d)arguments.callee(e,b.childNodes[d],c)}}}
function tn_Uc(a,b,c){if(1==b.nodeType)return b=c.createElement(b.nodeName),a.appendChild(b),b;3==b.nodeType?(b=c.createTextNode(b.nodeValue),a.appendChild(b)):4==b.nodeType?(b=c.createCDATASection(b.nodeValue),a.appendChild(b)):8==b.nodeType?(b=c.createComment(b.nodeValue),a.appendChild(b)):2==b.nodeType&&a.setAttribute(b.nodeName,b.nodeValue);return null}
function tn_Xc(a,b){var c=tn_2a(a),d;if(c.steps&&!c.absolute&&1==c.steps.length&&"child"==c.steps[0].axis&&0==c.steps[0].predicate.length)d=c.steps[0].nodetest.evaluate(b).d();else{d=!1;for(var e=b.node;!d&&e;){for(var f=c.evaluate(b.clone(e,0,[e])).c(),h=0;h<f.length;++h)if(f[h]==b.node){d=!0;break}e=e.parentNode}}return d};function tn__c(a,b){window[a]=b}tn__c("nxslProcess",tn_Wa);tn__c("xmlParse",tn_Ua);tn__c("xsltProcess",tn_Nc);tn__c("xmlText",tn_Ia);tn__c("xmlImportNode",tn_Ca);var tn_0c="http://www.gstatic.com/translate/infowindow/";function tn_1c(){return tn_0c+"transparent.png"}var tn_2c=Number.MAX_VALUE;var tn_3c="windo";function tn_J(a,b,c,d,e,f){var h=((b?b.ownerDocument:null)||document).createElement(a);c&&tn_K(h,c);d&&tn_4c(h,d);h.style.display="none";b&&!e&&(tn_L(b,h),b[tn_3c]&&(h[tn_3c]=b[tn_3c]));f||window.setTimeout(function(){h.style.display=""},0);return h}function tn_5c(a,b){var c=((b?b.ownerDocument:null)||document).createTextNode(a);b&&tn_L(b,c);return c}function tn_M(a){return tn_N(a)+"px"}function tn_K(a,b){var c=a.style;c.position="absolute";c.left=tn_M(b.x);c.top=tn_M(b.y)}
function tn_4c(a,b){var c=a.style;c.width=tn_M(b.width);c.height=tn_M(b.height)}function tn_O(a,b){a.style.width=tn_M(b)}function tn_P(a,b){a.style.height=tn_M(b)}function tn_(a){a.style.display="none"}function tn_Q(a){a.style.display=""}function tn_6c(a){a.style.visibility="hidden"}function tn_7c(a){a.style.visibility=""}function tn_8c(a){tn_9c(a,"hidden")}function tn_9c(a,b){a.style.overflow=b}var tn_R=Math.min,tn_S=Math.max,tn_N=Math.round;
function tn_T(a,b){try{a.style.cursor=b}catch(c){"pointer"==b&&tn_T(a,"hand")}}function tn_$c(a){tn_ad(a,"gmnoscreen");tn_bd(a,"gmnoprint")}function tn_cd(a,b,c){return window.setTimeout(function(){b.apply(a)},c)}function tn_dd(a){a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a}function tn_L(a,b){a.appendChild(b)}function tn_U(a){a.parentNode&&(a.parentNode.removeChild(a),tn_ed(a))}function tn_fd(a){for(var b;b=a.firstChild;)tn_ed(b),a.removeChild(b)}
function tn_gd(a,b){a.innerHTML!=b&&(tn_fd(a),a.innerHTML=b)}function tn_hd(a){tn_V.j()?a.style.MozUserSelect="none":(a.unselectable="on",a.onselectstart=tn_id)}function tn_jd(a,b){for(var c=a.length,d=0;d<c;++d)b(a[d],d)}function tn_kd(a,b,c){for(var d in a)(c||!a.hasOwnProperty||a.hasOwnProperty(d))&&b(d,a[d])}function tn_ld(a,b,c,d){c=c||0;for(d=d||b.length;c<d;++c)a.push(b[c])}function tn_id(){return!1}
function tn_md(a,b){1==tn_V.type?a.style.filter="alpha(opacity="+tn_N(100*b)+")":a.style.opacity=b}function tn_nd(a,b,c){a=tn_J("div",a,b,c);a.style.backgroundColor="black";tn_md(a,0.35);return a}function tn_W(a,b){var c=(a?a.ownerDocument:null)||document;if(a.currentStyle)return c=tn_od(b),a.currentStyle[c];if(c.defaultView&&c.defaultView.getComputedStyle)return(c=c.defaultView.getComputedStyle(a,""))?c.getPropertyValue(b):"";c=tn_od(b);return a.style[c]}var tn_pd="__mapsBaseCssDummy__";
function tn_qd(a,b,c){b=c?c:tn_W(a,b);if("number"==typeof b||isNaN(parseInt(b,10)))return b;if(2<b.length&&"px"==b.substring(b.length-2))return parseInt(b,10);(c=a.ownerDocument.getElementById(tn_pd))?a.parentNode.appendChild(c):(c=tn_J("div",a,new tn_a(0,0),new tn_X(0,0)),c.id=tn_pd,tn_6c(c));c.style.width="0px";c.style.width=b;return c.offsetWidth}var tn_rd="border-left-width",tn_sd="border-top-width";function tn_td(a){return new tn_X(tn_ud(a,tn_rd),tn_ud(a,tn_sd))}
function tn_ud(a,b){var c=tn_W(a,b);return isNaN(parseInt(c,10))?0:tn_qd(a,b,c)}function tn_od(a){return a.replace(/-(\w)/g,function(a,c){return(""+c).toUpperCase()})}function tn_vd(a){a.length=0}function tn_wd(a){var b=!1;a&&"object"==typeof a&&(b="function"==typeof Window?a instanceof Window:"object"==typeof a.navigator&&"object"==typeof a.history&&"object"==typeof a.document);return b}function tn_xd(a){return a=tn_wd(a)?a:a&&a[tn_3c]?a[tn_3c]:window}
function tn_yd(a,b){var c=tn_xd(b);return a[tn_3c]=c};function tn_zd(a,b,c){tn_Ad([a],function(a){b(a[0])},c)}
function tn_Ad(a,b,c){c=c||screen.width;var d=tn_J("div",window.document.body,new tn_a(-screen.width,-screen.height),new tn_X(c,screen.height)),e=[];for(c=0;c<a.length;c++){var f=tn_J("div",d,tn_a.ORIGIN);tn_L(f,a[c]);e.push(f)}window.setTimeout(function(){for(var c=[],f=new tn_X(0,0),m=0;m<e.length;m++){var l=e[m],g=new tn_X(l.offsetWidth,l.offsetHeight);c.push(g);l.removeChild(a[m]);tn_U(l);f.width=tn_S(f.width,g.width);f.height=tn_S(f.height,g.height)}tn_U(d);e=null;b(c,f)},0)};function tn_Bd(a,b,c,d,e,f,h){e&&1==tn_V.type?(b=tn_J("div",b,c,d),b.style.overflow="hidden",d&&f&&(b.sizingMethod="scale"),d=tn_J("img",b),tn_6c(d),tn_Cd(d,tn_Dd,tn_Ed)):(b=tn_J("img",b,c,d),h&&tn_Cd(b,tn_Dd,tn_Fd));h&&(b.hideAndTrackLoading=!0);tn_hd(b);1==tn_V.type&&(b.galleryImg="no");b.style.border=tn_M(0);b.style.padding=tn_M(0);b.style.margin=tn_M(0);b.oncontextmenu=tn_Gd;tn_Hd(b,a);return b}
function tn_Ed(){var a=this.parentNode;a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="+(a.sizingMethod?a.sizingMethod:"crop")+',src="'+this.src+'")';a.hideAndTrackLoading&&(a.loaded=!0)}function tn_Hd(a,b){"DIV"==a.tagName?(a.firstChild.src=b,a.src=b,a.hideAndTrackLoading&&(a.style.filter="",a.loaded=!1)):a.hideAndTrackLoading&&b!=tn_1c()?(b!=tn_1c()?(a.loaded=!1,a.pendingSrc=b):a.pendingSrc=null,a.src=tn_1c()):a.src=b}
function tn_Fd(){var a=this;a.src==tn_1c()&&a.pendingSrc?(a.src=a.pendingSrc,a.pendingSrc=null):a.loaded=!0};var tn_Id="click",tn_Jd="contextmenu",tn_Kd="dblclick",tn_Dd="load",tn_Ld="mousedown",tn_Md="mousewheel",tn_Nd="DOMMouseScroll",tn_Od="unload",tn_Pd="closeclick",tn_Qd="maximizeclick",tn_Rd="restoreclick",tn_Sd="maximizeend",tn_Td="restoreend",tn_Ud="clearlisteners",tn_Vd="logclick";var tn_Wd=!1;function tn_Y(){this.n=[]}function tn_Xd(){}tn_Y.instance=function(a){a||(a=window);a.gEventListenerPool||(a.gEventListenerPool=new tn_Y);return a.gEventListenerPool};tn_Y.remove=function(a){tn_Y.instance(tn_xd(a)).Ia(a)};tn_Y.prototype.Ia=function(a){var b=this.n.pop(),c=a.qa();c<this.n.length&&(this.n[c]=b,b.D(c));a.D(-1)};tn_Y.push=function(a){tn_Y.instance(tn_xd(a)).Ha(a)};tn_Y.prototype.Ha=function(a){this.n.push(a);a.D(this.n.length-1)};
tn_Y.prototype.clear=function(){for(var a=0;a<this.n.length;++a)this.n[a].D(-1);this.n=[]};function tn_Yd(a,b,c){a=new tn_Z(a,b,c,0);tn_Y.push(a);return a}function tn_Zd(a){a.remove();tn_Y.remove(a)}function tn__d(a){tn__(a,tn_Ud);tn_jd(tn_0d(a),function(a){a.remove();tn_Y.remove(a)})}function tn_0d(a,b){var c=[],d=a.__e_;d&&(b?d[b]&&tn_ld(c,d[b]):tn_kd(d,function(a,b){tn_ld(c,b)}));return c}
function tn_1d(a,b,c){var d=null,e=a.__e_;e?(d=e[b],d||(d=[],c&&(e[b]=d))):(d=[],c&&(a.__e_={},a.__e_[b]=d));return d}function tn__(a,b,c){var d=[];tn_ld(d,arguments,2);tn_jd(tn_0d(a,b),function(b){if(tn_Wd)b.apply(a,d);else try{b.apply(a,d)}catch(c){}})}
function tn_Cd(a,b,c){3==tn_V.type&&b==tn_Kd?(a["on"+b]=c,c=new tn_Z(a,b,c,3)):a.addEventListener?(a.addEventListener(b,c,!1),c=new tn_Z(a,b,c,1)):a.attachEvent?(c=tn_2d(a,c),a.attachEvent("on"+b,c),c=new tn_Z(a,b,c,2)):(a["on"+b]=c,c=new tn_Z(a,b,c,3));var d=tn_xd(a);a==d&&b==tn_Od||tn_Y.push(c);return c}function tn_0(a,b,c,d){c=tn_3d(c,d);return tn_Cd(a,b,c)}function tn_4d(a,b,c){tn_0(a,tn_Id,b,c);1==tn_V.type&&tn_0(a,tn_Kd,b,c)}
function tn_3d(a,b){return function(c){c||(c=window.event);c&&!c.target&&(c.target=c.srcElement);b.call(a,c,this)}}function tn_2d(a,b){return function(){return b.apply(a,arguments)}}function tn_Z(a,b,c,d){tn_d(a);tn_d("function"==typeof c);var e=this;e.q=a;e.F=b;e.I=c;e.Wa=d;e.wa=-1;tn_yd(e,a);tn_1d(a,b,!0).push(e)}
tn_Z.prototype.remove=function(){var a=this;switch(a.Wa){case 1:a.q.removeEventListener(a.F,a.I,!1);break;case 2:a.q.detachEvent("on"+a.F,a.I);break;case 3:a.q["on"+a.F]=null}tn_Da(tn_1d(a.q,a.F),a);a.q=null;a.I=null;a.remove=tn_Xd;a.apply=tn_Xd};tn_Z.prototype.qa=function(){return this.wa};tn_Z.prototype.D=function(a){this.wa=a};tn_Z.prototype.apply=function(a,b){return this.I.apply(a,b)};function tn_ed(a){tn_Va(a,tn__d)}
function tn_5d(a){a.type==tn_Id&&tn__(document,tn_Vd,a);1==tn_V.type?(window.event.cancelBubble=!0,window.event.returnValue=!1):(a.preventDefault(),a.stopPropagation())}function tn_6d(a){a.type==tn_Id&&tn__(document,tn_Vd,a);1==tn_V.type?window.event.cancelBubble=!0:a.stopPropagation()}function tn_Gd(a){1==tn_V.type?window.event.returnValue=!1:a.preventDefault()};var tn_7d="opera msie chrome applewebkit firefox camino mozilla".split(" "),tn_8d="x11; macintosh windows android ipad ipod iphone webos".split(" ");
function tn_1(a){this.agent=a;this.os=this.type=-1;this.osVersion=0;this.cpu=-1;this.build=this.revision=this.version=0;a=a.toLowerCase();for(var b=0;b<tn_7d.length;b++){var c=tn_7d[b];if(-1!=a.indexOf(c)){this.type=b;b=RegExp(c+"[ /]?([0-9]+(.[0-9]+)?)");if(b=b.exec(a))this.version=parseFloat(b[1]);break}}6==this.type&&(b=/^Mozilla\/.*Gecko\/.*(Minefield|Shiretoko)[ /]?([0-9]+(.[0-9]+)?)/,b=b.exec(this.agent))&&(this.type=4,this.version=parseFloat(b[2]));3==this.type&&(b=/^.*Version\/?([0-9]+(.[0-9]+)?)/,
b=b.exec(this.agent))&&(this.build=this.version,this.version=parseFloat(b[1]));0==this.type&&(b=/^Opera\/9.[89].*Version\/?([0-9]+(.[0-9]+)?)/,b=b.exec(this.agent))&&(this.version=parseFloat(b[1]));for(b=0;b<tn_8d.length;b++)if(c=tn_8d[b],-1!=a.indexOf(c)){this.os=b;break}1==this.os?(b=/Mac OS X[ ]+([0-9]+)[\._]([0-9]+)/,(b=b.exec(this.agent))&&3<=b.length&&(this.osVersion=parseFloat(b[1]+"."+b[2]))):2==this.os&&(b=/Windows NT ([0-9]+.[0-9]+)/,(b=b.exec(this.agent))&&2<=b.length&&(this.osVersion=
parseFloat(b[1])));1==this.os&&-1!=a.indexOf("intel")&&(this.cpu=0);b=/\brv:\s*(\d+\.\d+)/.exec(a);this.j()&&b&&(this.revision=parseFloat(b[1]));1==this.type&&(this.cb=/win64;/.test(a))}tn_1.ab="F9152AEC-3462-4632-8087-EEE3C3CDDA24";tn_1.bb="application/geplugin";tn_1.$a="getSelf";tn_1.prototype.j=function(){return 4==this.type||6==this.type||5==this.type};tn_1.OS_NAMES={};tn_1.OS_NAMES[2]="windows";tn_1.OS_NAMES[1]="macos";tn_1.OS_NAMES[0]="unix";tn_1.OS_NAMES[3]="android";tn_1.OS_NAMES[6]="iphone";
tn_1.OS_NAMES[-1]="other";tn_1.BROWSER_NAMES={};tn_1.BROWSER_NAMES[1]="ie";tn_1.BROWSER_NAMES[4]="firefox";tn_1.BROWSER_NAMES[2]="chrome";tn_1.BROWSER_NAMES[3]="safari";tn_1.BROWSER_NAMES[0]="opera";tn_1.BROWSER_NAMES[5]="camino";tn_1.BROWSER_NAMES[6]="mozilla";tn_1.BROWSER_NAMES[-1]="other";var tn_V=new tn_1(navigator.userAgent);tn_a.ORIGIN=new tn_a(0,0);tn_a.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function tn_X(a,b){this.width=a;this.height=b}tn_X.ZERO=new tn_X(0,0);tn_X.prototype.toString=function(){return"("+this.width+", "+this.height+")"};function tn_9d(a){this.minX=this.minY=tn_2c;this.maxX=this.maxY=-tn_2c;var b=arguments;if(a&&a.length)for(b=0;b<a.length;b++)this.extend(a[b]);else 4<=b.length&&(this.minX=b[0],this.minY=b[1],this.maxX=b[2],this.maxY=b[3])}
tn_9d.prototype.min=function(){return new tn_a(this.minX,this.minY)};tn_9d.prototype.max=function(){return new tn_a(this.maxX,this.maxY)};tn_9d.prototype.toString=function(){return"("+this.min()+", "+this.max()+")"};tn_9d.prototype.extend=function(a){var b=this;b.minX=tn_R(b.minX,a.x);b.maxX=tn_S(b.maxX,a.x);b.minY=tn_R(b.minY,a.y);b.maxY=tn_S(b.maxY,a.y)};
tn_9d.intersection=function(a,b){return new tn_9d([new tn_a(tn_S(a.minX,b.minX),tn_S(a.minY,b.minY)),new tn_a(tn_R(a.maxX,b.maxX),tn_R(a.maxY,b.maxY))])};function tn_bd(a,b){var c=a.className?""+a.className:"";if(c){for(var c=c.split(/\s+/),d=!1,e=0;e<c.length;++e)if(c[e]==b){d=!0;break}d||c.push(b);a.className=c.join(" ")}else a.className=b}function tn_ad(a,b){var c=a.className?""+a.className:"";if(c&&-1!=c.indexOf(b)){for(var c=c.split(/\s+/),d=0;d<c.length;++d)c[d]==b&&c.splice(d--,1);a.className=c.join(" ")}};function tn_$d(){}tn_$d.monitor=function(){};tn_$d.monitorAll=function(){};tn_$d.dump=function(){};function tn_2(){var a=tn_J("div",document.body),b=a.style;b.position="absolute";b.left=tn_M(7);b.bottom=tn_M(4);b.zIndex=1E4;var c=tn_nd(a,new tn_a(2,2)),d=tn_J("div",a),b=d.style;b.position="relative";b.zIndex=1;b.fontFamily="Verdana,Arial,sans-serif";b.fontSize="small";b.border="1px solid black";var e=[["Clear",this.clear],["Close",this.close]],f=tn_J("div",d),b=f.style;b.position="relative";b.zIndex=2;b.backgroundColor="#979797";b.color="white";b.fontSize="85%";b.padding=tn_M(2);tn_T(f,"default");
tn_hd(f);tn_5c("Log",f);for(b=0;b<e.length;b++){var h=e[b];tn_5c(" - ",f);var p=tn_J("span",f);p.style.textDecoration="underline";tn_5c(h[0],p);tn_4d(p,this,h[1]);tn_T(p,"pointer")}d=tn_J("div",d);b=d.style;b.backgroundColor="white";b.width="80em";b.height="10em";b.overflow=tn_V.j()?"-moz-scrollbars-vertical":"auto";tn_Cd(d,tn_Ld,tn_6d);this.K=d;this.U=a;this.i=c}tn_2.instance=function(){var a=tn_2.q;a||(a=new tn_2,tn_2.q=a);return a};
tn_2.prototype.write=function(a,b){var c=this.oa();b&&(c=tn_J("span",c),c.style.color=b);tn_5c(a,c);this.Ja()};tn_2.prototype.clear=function(){this.K.innerHTML=""};tn_2.prototype.close=function(){tn_U(this.U)};tn_2.prototype.oa=function(){var a=tn_J("div",this.K),b=a.style;b.fontSize="85%";b.borderBottom="1px solid silver";b.paddingBottom=tn_M(2);b=tn_J("div",a);b.style.color="gray";b.style.fontSize="75%";tn_5c(this.Ra(),b);return a};
tn_2.prototype.Ja=function(){this.K.scrollTop=this.K.scrollHeight;this.Pa()};tn_2.prototype.Ra=function(){var a=new Date;return this.B(a.getHours(),2)+":"+this.B(a.getMinutes(),2)+":"+this.B(a.getSeconds(),2)+":"+this.B(a.getMilliseconds(),3)};tn_2.prototype.B=function(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c};tn_2.prototype.Pa=function(){tn_4c(this.i,new tn_X(this.U.offsetWidth,this.U.offsetHeight))};var tn_ae="overflow",tn_be="position",tn_ce="visible",tn_de="static",tn_ee="BODY";
function tn_fe(a,b){for(var c=new tn_a(0,0);a&&a!=b;){a.nodeName==tn_ee&&tn_ge(c,a);var d=tn_td(a);c.x+=d.width;c.y+=d.height;a.nodeName==tn_ee&&tn_V.j()||(c.x+=a.offsetLeft,c.y+=a.offsetTop);tn_V.j()&&1.8<=tn_V.revision&&a.offsetParent&&a.offsetParent.nodeName!=tn_ee&&tn_W(a.offsetParent,tn_ae)!=tn_ce&&(d=tn_td(a.offsetParent),c.x+=d.width,c.y+=d.height);a.offsetParent&&(c.x-=a.offsetParent.scrollLeft,c.y-=a.offsetParent.scrollTop);if(1!=tn_V.type&&a.offsetParent&&a.offsetParent.nodeName==tn_ee&&
tn_W(a.offsetParent,tn_be)==tn_de&&(0==tn_V.type&&tn_W(a,tn_be)!=tn_de||0!=tn_V.type&&"absolute"==tn_W(a,tn_be))){tn_V.j()&&(c.x-=self.pageXOffset,c.y-=self.pageYOffset,d=tn_td(a.offsetParent.parentNode),c.x+=d.width,c.y+=d.height);break}3==tn_V.type&&a.offsetParent&&(d=tn_td(a.offsetParent),c.x-=d.width,c.y-=d.height);a=a.offsetParent}1==tn_V.type&&!b&&document.documentElement&&(c.x+=document.documentElement.clientLeft,c.y+=document.documentElement.clientTop);return b&&null==a?(d=tn_fe(b),new tn_a(c.x-
d.x,c.y-d.y)):c}
function tn_ge(a,b){var c=!1;if(tn_V.j()){var c=tn_W(b,tn_ae)!=tn_ce&&tn_W(b.parentNode,tn_ae)!=tn_ce,d=tn_W(b,tn_be)!=tn_de;if(d||c){a.x+=tn_qd(b,"margin-left");a.y+=tn_qd(b,"margin-top");var e=tn_td(b.parentNode);a.x+=e.width;a.y+=e.height}d&&(a.x+=tn_qd(b,"left"),a.y+=tn_qd(b,"top"))}if((tn_V.j()||1==tn_V.type)&&"BackCompat"!=document.compatMode||c)self.pageYOffset?(a.x-=self.pageXOffset,a.y-=self.pageYOffset):(a.x-=document.documentElement.scrollLeft,a.y-=document.documentElement.scrollTop)}
function tn_he(a,b){if("undefined"!=typeof a.offsetX){var c=tn_dd(a),d=tn_fe(c,b),e=new tn_a(a.offsetX,a.offsetY);3==tn_V.type&&(c=tn_td(c),e.x-=c.width,e.y-=c.height);return new tn_a(d.x+e.x,d.y+e.y)}return"undefined"!=typeof a.clientX?(d=3==tn_V.type?new tn_a(a.pageX-self.pageXOffset,a.pageY-self.pageYOffset):new tn_a(a.clientX,a.clientY),e=tn_fe(b),new tn_a(d.x-e.x,d.y-e.y)):tn_a.ORIGIN};function tn_ie(a){this.ticks=a;this.tick=0}tn_ie.prototype.reset=function(){this.tick=0};tn_ie.prototype.next=function(){this.tick++;var a=Math.PI*(this.tick/this.ticks-0.5);return(Math.sin(a)+1)/2};tn_ie.prototype.more=function(){return this.tick<this.ticks};tn_ie.prototype.extend=function(){this.tick>this.ticks/3&&(this.tick=tn_N(this.ticks/3))};var tn_je=!1;function tn_ke(a,b,c){this.name=a;"string"==typeof b&&(a=tn_J("div",null),tn_gd(a,b),b=a);this.contentElem=b;b.style.zIndex=9500;this.onclick=c}function tn_3(){this.da=new tn_b(0,0,0,0);this.ba=tn_X.ZERO;this.f=[];this.l=[];this.P=[];this.ha=[];this.s=this.u=0;this.p=this.T(tn_X.ZERO);this.g={};this.m=this.R=this.Aa=!1;this.ga=new tn_a(8,8);this.aa="ltr"}
tn_3.prototype.create=function(a,b){var c=this.g,d=tn_le(c,a,[["iw_n",628,6,0,0,"iw_n1"],["iw_n",628,6,0,0,"iw_n2"],["iw_w",6,598,0,0],["iw_e",6,598,0,0],["iw_s0",628,6,0,0,"iw_s1"],["iw_s0",628,6,0,0,"iw_s2"],["iw_c",628,598,0,0]]),e=new tn_X(6,6);tn_4(c,d,"iw_nw",e);tn_4(c,d,"iw_ne",e);tn_4(c,d,"iw_xtap",new tn_X(32,21));tn_4(c,d,"iw_xtap_l",new tn_X(32,21));tn_4(c,d,"iw_xtap_u",new tn_X(32,21));tn_4(c,d,"iw_xtap_ul",new tn_X(32,21));tn_4(c,d,"iw_xtap_rd",new tn_X(21,32));tn_4(c,d,"iw_xtap_ld",
new tn_X(21,32));tn_4(c,d,"iw_sw0",e,"iw_sw");tn_4(c,d,"iw_se0",e,"iw_se");tn_$c(d);this.e=d;var e=new tn_X(8,8),f=tn_le(c,b,[["iws_n",628,8,0,0,"iws_n1"],["iws_n",628,8,0,0,"iws_n2"],["iws_w",8,598,0,0],["iws_e",8,598,0,0],["iws_s",628,8,0,0,"iws_s1"],["iws_s",628,8,0,0,"iws_s2"],["iws_c",628,598,0,0]]);tn_4(c,f,"iws_nw",e);tn_4(c,f,"iws_ne",e);tn_4(c,f,"iws_sw",e);tn_4(c,f,"iws_se",e);tn_4(c,f,"iws_tap",new tn_X(37,16));tn_4(c,f,"iws_tap_l",new tn_X(32,16));tn_4(c,f,"iws_tap_u",new tn_X(37,26));
tn_4(c,f,"iws_tap_ul",new tn_X(32,26));tn_4(c,f,"iws_tap_rd",new tn_X(16,37));tn_4(c,f,"iws_tap_ld",new tn_X(26,37));tn_4(c,f,"iws_tab_dl",new tn_X(8,28));tn_4(c,f,"iws_tab_dr",new tn_X(14,28));tn_4(c,f,"iws_tab_l",new tn_X(8,28));tn_4(c,f,"iws_tab_r",new tn_X(14,28));tn_(c.iws_tab_dl);tn_(c.iws_tab_dr);tn_(c.iws_tab_l);tn_(c.iws_tab_r);tn_$c(f);this.i=f;e=new tn_X(14,13);f=tn_4(c,d,"close",e,"close",!0);f.style.zIndex=1E4;tn_T(f,"pointer");tn_4d(f,this,this.Fa);f=tn_4(c,d,"maximize",e,"maximize",
!0);f.style.zIndex=1E4;tn_6c(f);tn_T(f,"pointer");tn_4d(f,this,this.maximize);c=tn_4(c,d,"restore",e,"restore",!0);c.style.zIndex=10001;tn_6c(c);tn_T(c,"pointer");tn_4d(c,this,this.restore);tn_0(d,tn_Ld,this,this.X);tn_0(d,tn_Kd,this,this.pa);tn_0(d,tn_Id,this,this.X);tn_0(d,tn_Jd,this,tn_6d);tn_0(d,tn_Md,this,tn_6d);tn_0(d,tn_Nd,this,tn_6d);this.Oa();this.hide()};tn_3.prototype.remove=function(){tn_U(this.i);tn_U(this.e)};
tn_3.prototype.ka=function(a){a?(tn_Q(this.g.maximize),tn_Q(this.g.restore)):(tn_(this.g.maximize),tn_(this.g.restore))};tn_3.prototype.O=function(a){this.g.close.style.visibility=a?"visible":"hidden"};tn_3.prototype.La=function(a){this.aa=!0===a||"rtl"===a?"rtl":"ltr"};tn_3.prototype.za=function(a){this.Aa=a};tn_3.prototype.Ba=function(a){this.Ca=a};tn_3.prototype.ja=function(a){this.R=a};
tn_3.prototype.M=function(a){if(!a.getClientRects)return this.o(tn_ga(a));var b=this.z(),c=this.g,d=b.width,e=b.height,f=window.innerWidth||document.body.scrollWidth,b=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,h=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_(c.iw_xtap);tn_(c.iw_xtap_l);tn_(c.iw_xtap_u);tn_(c.iw_xtap_ul);tn_(c.iw_xtap_ld);tn_(c.iw_xtap_rd);tn_(c.iws_tap);tn_(c.iws_tap_l);tn_(c.iws_tap_u);tn_(c.iws_tap_ul);tn_(c.iws_tap_ld);
tn_(c.iws_tap_rd);var p,m,l,g,c=a.getClientRects(),k=Array(c.length),q=tn_ga(a);a=c[0].top-q.y;for(var n=0;n<c.length;++n){k[n]={left:c[n].left,right:c[n].right,top:c[n].top,bottom:c[n].bottom};0<n&&k[n].bottom==k[n-1].bottom&&(k[n].left==k[n-1].right?(k[n].left=k[n-1].left,k[n].top=tn_R(k[n].top,k[n-1].top)):k[n].right==k[n-1].left&&(k[n].right=k[n-1].right,k[n].top=tn_R(k[n].top,k[n-1].top)));if(!p||k[n].left<=p.left)p=k[n];if(!m||k[n].right>=m.right)m=k[n];if(!l||k[n].top<=l.top)l=k[n];if(!g||
k[n].bottom>=g.bottom)g=k[n]}if(this.m&&21+d+6+12+m.right<f)return this.o(new tn_b(p.left+b,m.top-a,m.right-p.left,m.bottom-m.top));if(this.m&&18+d+21<p.left)return this.o(new tn_b(p.left+b,p.top-a,m.right-p.left,p.bottom-p.top));this.R&&21+e+6+12+(1<this.f.length?20:0)>q.y-(this.Ca?h:0)?(d=this.m,this.m=!1,l=this.o(new tn_b(g.left+b,l.top-a,g.right-g.left,g.bottom-l.top))):(d=this.m,this.m=!1,l=this.o(new tn_b(l.left+b,l.top-a,l.right-l.left,g.bottom-l.top)));this.m=d;return l};
tn_3.prototype.o=function(a,b){var c=this.z(),d=this.g,e=c.width,f=c.height,h=document.body.scrollWidth,p=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,m=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_(d.iw_xtap);tn_(d.iw_xtap_l);tn_(d.iw_xtap_u);tn_(d.iw_xtap_ul);tn_(d.iw_xtap_ld);tn_(d.iw_xtap_rd);tn_(d.iws_tap);tn_(d.iws_tap_l);tn_(d.iws_tap_u);tn_(d.iws_tap_ul);tn_(d.iws_tap_ld);tn_(d.iws_tap_rd);var l=0,c=0,g,k,q,n,s,r=0,t=this.m;
t&&21+e+6+12+a.x+a.w<p+h?(k=!0,f=d.iw_xtap_ld,m=d.iws_tap_ld):t&&18+e+21+p<a.x?(q=!0,f=d.iw_xtap_rd,m=d.iws_tap_rd,c=5):(this.R&&21+f+6+12+(1<this.f.length?20:0)+(this.Ca?m:0)>a.y?(f=d.iw_xtap_u,m=d.iws_tap_u,l=0,g=!0):(f=d.iw_xtap,m=d.iws_tap,l=0),tn_N(a.x+a.w/2)+32+6+12>p+h&&(f==d.iw_xtap_u?(f=d.iw_xtap_ul,m=d.iws_tap_ul):(f=d.iw_xtap_l,m=d.iws_tap_l),c=5,l=32),n=tn_N((e-32)/2),this.Aa&&(n+6+12+l+p>a.x+tn_N(a.w/2)?(n=a.x+tn_N(a.w/2)-6-12-l-p,0>n&&(r=tn_R(-n,tn_N(a.w/2)),n=0)):a.x+tn_N(a.w/2)-l+
e-n+18>p+h&&(g?(f=d.iw_xtap_ul,m=d.iws_tap_ul):(f=d.iw_xtap_l,m=d.iws_tap_l),c=5,l=32,n=a.x+tn_N(a.w/2)-l+e+6+12-h-p,n>e-32&&(r=tn_S(e-32-n,-tn_N(a.w/2)),n=e-32))),s=e-32-n);tn_Q(f);tn_Q(m);this.Va=k?0:q?6+e+21:6+n+l;e=this.ba=b||tn_X.ZERO;r=this.Va-r;d=k||q?6:g?0:this.ra().height+(1<this.f.length?20:0);r-=e.width;d-=e.height;this.eb=e=new tn_a(a.x+(k?a.w:q?0:a.w/2)-r,a.y+(k||q?a.h/2:g?a.h:0)-d);tn_K(this.e,e);tn_K(this.i,e);this.da=a;this.Ea=void 0;return this.Ga(k,q,g,n,s,f,m,c)};
tn_3.prototype.Ga=function(a,b,c,d,e,f,h,p){var m=!(a||b||c);this.Q=f;this.N=h;var l=this.z(),g=this.g,k=l.width,q=l.height,n=1<this.f.length?this.u:0;c?(tn_O(g.iw_n1,tn_S(d,0)),tn_O(g.iw_n2,tn_S(e,0)),tn_O(g.iw_s1,k-n),tn_O(g.iw_s2,0),tn_O(g.iws_n1,tn_S(d,0)),tn_O(g.iws_n2,tn_S(e,0)),tn_O(g.iws_s1,k-n),tn_O(g.iws_s2,0)):m?(tn_O(g.iw_n1,k-n),tn_O(g.iw_n2,0),tn_O(g.iw_s1,tn_S(d,0)),tn_O(g.iw_s2,tn_S(e,0)),tn_O(g.iws_n1,k-n),tn_O(g.iws_n2,0),tn_O(g.iws_s1,tn_S(d,0)),tn_O(g.iws_s2,tn_S(e,0))):(tn_O(g.iw_n1,
k),tn_O(g.iw_n2,0),tn_O(g.iw_s1,k-n),tn_O(g.iw_s2,0),tn_O(g.iws_n1,k),tn_O(g.iws_n2,0),tn_O(g.iws_s1,k-n),tn_O(g.iws_s2,0));tn_4c(g.iw_c,l);a?(tn_P(g.iw_w,tn_S(q-32,0)),tn_P(g.iw_e,tn_S(q,32)),tn_P(g.iws_w,tn_S(q-32,0)),tn_P(g.iws_e,tn_S(q,32))):b?(tn_P(g.iw_e,tn_S(q-32,0)),tn_P(g.iw_w,tn_S(q,32)),tn_P(g.iws_e,tn_S(q-32,0)),tn_P(g.iws_w,tn_S(q,32))):(tn_P(g.iw_w,q),tn_P(g.iw_e,q),tn_P(g.iws_w,q),tn_P(g.iws_e,q));e=a?15:0;var l=e+5-2,s=e+6,r=s+5,t=s+k,z=t+5,B=a?0:b?t:s+d,E=B+p,D=B+32,F=D+5,k=c?15:
!a&&!b&&1<this.f.length?20:0,A=k+5-2,u=k+6,C=u+5,v=u+(a||b?tn_S(q,32):q),x=v+5,q=c||a||b?v:0;p=q+5-(c||a||b?0:2);d=c||a||b?v+6-1:0;var G=new tn_a(s,v),H=new tn_a(r,x),I=new tn_a(s,k),J=new tn_a(r,A);tn_K(g.iw_nw,new tn_a(e,k));tn_K(g.iws_nw,new tn_a(l,A));m?(tn_K(g.iw_n1,new tn_a(s+n,k)),tn_K(g.iws_n1,new tn_a(r+n,A)),tn_K(g.iw_s1,G),tn_K(g.iws_s1,H),tn_K(g.iw_s2,new tn_a(D,v)),tn_K(g.iws_s2,new tn_a(F,x)),tn_(g.iws_tab_dl),tn_(g.iws_tab_dr),tn_Q(g.iws_tab_l),tn_Q(g.iws_tab_r),tn_K(g.iws_tab_l,new tn_a(l,
p)),tn_K(g.iws_tab_r,new tn_a(r+n-14,p))):(tn_K(g.iw_n1,I),tn_K(g.iws_n1,J),tn_K(g.iw_s2,G),tn_K(g.iws_s2,H),tn_K(g.iw_s1,new tn_a(s+n,v)),tn_K(g.iws_s1,new tn_a(r+n,x)),tn_Q(g.iws_tab_dl),tn_Q(g.iws_tab_dr),tn_(g.iws_tab_l),tn_(g.iws_tab_r),tn_K(g.iws_tab_dl,new tn_a(l,p)),tn_K(g.iws_tab_dr,new tn_a(r+n-14,p)));c?(tn_K(g.iw_n2,new tn_a(D,k)),tn_K(g.iws_n2,new tn_a(F,A))):(tn_K(g.iw_n2,I),tn_K(g.iws_n2,J));tn_K(g.iw_ne,new tn_a(t,k));tn_K(g.iws_ne,new tn_a(z,A));tn_K(g.iw_w,new tn_a(e,u+(a?32:0)));
tn_K(g.iws_w,new tn_a(l,C+(a?32:0)));tn_K(g.iw_c,new tn_a(s,u));tn_K(g.iws_c,new tn_a(r,C));tn_O(g.iw_c,t-s);tn_P(g.iw_c,v-u);tn_O(g.iws_c,z-r);tn_P(g.iws_c,x-C);tn_K(g.iw_e,new tn_a(t,u+(b?32:0)));tn_K(g.iws_e,new tn_a(z,C+(b?32:0)));tn_K(g.iw_sw,new tn_a(e,v));tn_K(g.iws_sw,new tn_a(l,x));tn_K(g.iw_se,new tn_a(t,v));tn_K(g.iws_se,new tn_a(z,x));a?(tn_K(f,new tn_a(0,u)),tn_K(h,new tn_a(0,u))):b?(tn_K(f,new tn_a(t,u)),tn_K(h,new tn_a(z,u))):c?(tn_K(f,new tn_a(B,0)),tn_K(h,new tn_a(E,0))):(tn_K(f,
new tn_a(B,v)),tn_K(h,new tn_a(E,x)));a="rtl"==this.aa?-0+s:t-14+0;b=u-0;tn_K(g.close,new tn_a(a,b));"hidden"!=g.close.style.visibility&&(a="rtl"==this.aa?a+16:a-16);a=new tn_a(a,b);tn_K(g.maximize,a);tn_K(g.restore,a);this.ga=new tn_a(e+8,k+8);for(a=0;a<this.l.length;a++)b=this.l[a],tn_K(b,this.ga);if(2>this.f.length)tn_(g.iws_tab_l),tn_(g.iws_tab_r),tn_(g.iws_tab_dl),tn_(g.iws_tab_dr),tn_Q(g.iw_sw),tn_Q(g.iws_sw),tn_Q(g.iw_nw),tn_Q(g.iws_nw);else for(m?(tn_(g.iw_nw),tn_(g.iws_nw),tn_Q(g.iw_sw),
tn_Q(g.iws_sw)):(tn_(g.iw_sw),tn_(g.iws_sw),tn_Q(g.iw_nw),tn_Q(g.iws_nw)),a=0;a<this.f.length;++a){g=this.f[a];k=g.images;f=g.textWidth;b=g.labelNode;var r=b.style,w;0<a&&(w=this.ha[a-1]);tn_(k.iw_tabback_dl);tn_(k.iw_tabback_dm);tn_(k.iw_tabback_dr);tn_(k.iw_tabback_l);tn_(k.iw_tabback_m);tn_(k.iw_tabback_r);tn_(k.iw_tab_dl);tn_(k.iw_tab_dm);tn_(k.iw_tab_dr);tn_(k.iw_tab_l);tn_(k.iw_tab_m);tn_(k.iw_tab_r);tn_(k.iws_tab_m);tn_(k.iws_tab_dm);w?(tn_(w.iws_tab_do),tn_(w.iws_tab_o)):(tn_(k.iw_tab_1l),
tn_(k.iw_tab_1dl),tn_(k.iw_tabback_1l),tn_(k.iw_tabback_1dl),tn_(k.iws_tab_1l),tn_(k.iws_tab_1dl));var y;c=this.e.style.zIndex;m?(this.s==a?(h=0==a?k.iw_tab_1l:k.iw_tab_l,n=k.iw_tab_m,s=k.iw_tab_r,++c):(h=0==a?k.iw_tabback_1l:k.iw_tabback_l,n=k.iw_tabback_m,s=k.iw_tabback_r),k=k.iws_tab_m,w&&(y=w.iws_tab_o),r.paddingTop=tn_M(4),r.paddingBottom=tn_M(0)):(this.s==a?(h=0==a?k.iw_tab_1dl:k.iw_tab_dl,n=k.iw_tab_dm,s=k.iw_tab_dr,++c):(h=0==a?k.iw_tabback_1dl:k.iw_tabback_dl,n=k.iw_tabback_dm,s=k.iw_tabback_dr),
k=k.iws_tab_dm,w&&(y=w.iws_tab_do),r.paddingTop=tn_M(4),r.paddingBottom="");tn_Q(h);tn_Q(n);tn_Q(s);tn_Q(k);r=g.offset+(0==a?6:11);tn_K(h,new tn_a(e+g.offset,q));tn_K(n,new tn_a(e+r,q));tn_O(n,f);tn_K(k,new tn_a(l+2+r,p));tn_O(k,f);tn_K(s,new tn_a(e+r+f,q));y&&(tn_Q(y),tn_K(y,new tn_a(l+r-14+2,p)),y.parentNode||tn_L(this.i,y));h.style.zIndex=c;n.style.zIndex=c;s.style.zIndex=c;f=f+2+3;tn_O(b,f);tn_K(b,new tn_a(e+r-2,d));tn_Q(b);b.style.zIndex=c+1;!b.parentNode&&0<g.textWidth&&tn_L(this.e,b)}};
tn_3.prototype.C=function(){this.Ea?this.M(this.Ea,this.ba):this.da&&this.o(this.da,this.ba)};tn_3.prototype.z=function(){return new tn_X(tn_S(this.p.width,this.u),this.p.height)};tn_3.prototype.reset=function(a,b,c,d,e){this.A(c,b,e);this.o(a,d);this.show();tn_6c(this.g.restore)};tn_3.prototype.hide=function(){this.Q&&tn_(this.Q);this.N&&tn_(this.N);tn_(this.e);tn_(this.i)};tn_3.prototype.show=function(){this.ya()&&(tn_Q(this.e),tn_Q(this.i),this.Q&&tn_Q(this.Q),this.N&&tn_Q(this.N))};
tn_3.prototype.Oa=function(){this.db=!0};tn_3.prototype.ya=function(){return"none"==this.e.style.display};tn_3.prototype.Ka=function(a){if(a!=this.s){this.ea(a);var b=this.l;tn_jd(b,tn_);tn_Q(b[a]);var c=this;window.setTimeout(function(){c.C()},0)}};tn_3.prototype.Fa=function(){tn__(this,tn_Pd)};
tn_3.prototype.maximize=function(a){if(!this.J){tn__(this,tn_Qd);tn_7c(this.g.restore);this.Qa=this.p;this.Za=this.f;this.Ya=this.s;this.r=this.r||new tn_X(628,598);var b=new tn_X(4+this.r.width,4+this.r.height);tn_V.j()&&(b.width+=1);this.$(b,a)}};tn_3.prototype.restore=function(a){this.J&&(tn__(this,tn_Rd),tn_6c(this.g.restore),this.A(this.r,this.Za,this.Ya),this.Ta=this.Qa,this.$(this.Qa,a))};tn_3.prototype.$=function(a,b){this.Z=new tn_ie(!0===b?1:10);this.H=this.p;this.ta=a;this.V()};
tn_3.prototype.V=function(){var a=this.Z.next();this.Z.more()&&tn_cd(this,this.V,10);var b=this.H.width+(this.ta.width-this.H.width)*a,a=this.H.height+(this.ta.height-this.H.height)*a;this.L(new tn_X(b,a));this.C();this.Sa();this.Z.more()||this.sa()};tn_3.prototype.sa=function(){this.J?(this.J=!1,tn__(this,tn_Td)):(this.J=!0,tn__(this,tn_Sd),this.r&&this.Da&&this.A(this.r,this.Da,this.Ua))};tn_3.prototype.L=function(a){return a=this.p=this.T(a)};
tn_3.prototype.pa=function(a){if(1==tn_V.type)tn_5d(a);else{var b=tn_he(a,this.e);b.y<=this.Y()&&tn_5d(a)}};tn_3.prototype.X=function(a){if(1==tn_V.type)tn_6d(a);else{var b=tn_he(a,this.e);b.y<=this.Y()&&(a.cancelDrag=!0)}};tn_3.prototype.Y=function(){return this.z().height+12};tn_3.prototype.ra=function(){var a=this.z();return new tn_X(a.width+12,a.height+21+6)};
tn_3.prototype.A=function(a,b,c){this.na();this.Ta=a;a=new tn_X(4+a.width,4+a.height);tn_V.j()&&(a.width+=1);var d=this.L(a),e=[];this.f=e;var f=c||0;a=new tn_X(d.width+-4,d.height+-4);var h=this.ga,p=this.l=[];for(c=0;c<b.length;c++){var m=tn_J("div",this.e,h,a);tn_8c(m);c!=f&&tn_(m);m.style.zIndex=10;tn_L(m,b[c].contentElem);p.push(m)}if(1<b.length){a=[];h=new tn_X(11,26);p=new tn_X(14,26);this.xa();for(c=0;c<b.length;++c){var l={images:b[c].images||{},textWidth:b[c].textWidth||0,offset:b[c].offset||
0,name:b[c].name,contentElem:b[c].contentElem,onclick:b[c].onclick},g=l.images;tn_le(g,this.e,[["iw_tabback_dm",1,26,0,0],["iw_tabback_m",1,26,0,0],["iw_tab_dm",1,26,0,0],["iw_tab_m",1,26,0,0]]);tn_4(g,this.e,"iw_tabback_dl",h);tn_4(g,this.e,"iw_tabback_dr",p);tn_4(g,this.e,"iw_tabback_l",h);tn_4(g,this.e,"iw_tabback_r",p);tn_4(g,this.e,"iw_tab_dl",h);tn_4(g,this.e,"iw_tab_dr",p);tn_4(g,this.e,"iw_tab_l",h);tn_4(g,this.e,"iw_tab_r",p);tn_le(g,this.i,[["iws_tab_dm",1,28,0,0],["iws_tab_m",1,28,0,0]]);
m=function(a,b){tn_(b);a.P.push(b)};if(0==c){var k=new tn_X(6,26);tn_4(g,this.e,"iw_tab_1dl",k);tn_4(g,this.e,"iw_tab_1l",k);tn_4(g,this.e,"iw_tabback_1dl",k);tn_4(g,this.e,"iw_tabback_1l",k);k=new tn_X(8,28);tn_4(g,this.i,"iws_tab_1dl",k);tn_4(g,this.i,"iws_tab_1l",k);m(this,g.iw_tab_1dl);m(this,g.iw_tab_1l);m(this,g.iw_tabback_1dl);m(this,g.iw_tabback_1l);m(this,g.iws_tab_1dl);m(this,g.iws_tab_1l)}m(this,g.iw_tabback_dl);m(this,g.iw_tabback_dm);m(this,g.iw_tabback_dr);m(this,g.iw_tabback_l);m(this,
g.iw_tabback_m);m(this,g.iw_tabback_r);m(this,g.iw_tab_dl);m(this,g.iw_tab_dm);m(this,g.iw_tab_dr);m(this,g.iw_tab_l);m(this,g.iw_tab_m);m(this,g.iw_tab_r);m(this,g.iws_tab_dm);m(this,g.iws_tab_m);g=document.createElement("div");l.labelNode=g;tn_P(g,20);k=g.style;tn_8c(g);k.fontWeight="bold";k.fontFamily="Arial,sans-serif";k.fontSize=tn_M(12);k.textAlign="center";k.display="inline";tn_me(g);tn_5c(l.name,g);(function(a,b,c,d){tn_4d(d,a,function(){a.Ka(b);c&&c()})})(this,c,b[c].onclick,g);this.P.push(g);
a.push(g);this.f.push(l);0<c&&(l={},g=new tn_X(14,28),tn_4(l,this.i,"iws_tab_do",g),tn_4(l,this.i,"iws_tab_o",g),m(this,l.iws_tab_do),m(this,l.iws_tab_o),this.ha.push(l))}var q=this;tn_Ad(a,function(a){var b;if(a.length==e.length){for(var c=0;c<a.length;++c){var g=b=e[c];0!=a[c].width&&(g.textWidth=tn_S(0,a[c].width-2-3));tn_Q(g.labelNode);tn_L(q.e,g.labelNode);if(0<c){var h=e[c-1];g.offset=h.offset+h.textWidth+(1==c?6:11)+14-11}}q.u=b.offset+b.textWidth+14+11-6;if(q.u+30>d.width)for(q.L(new tn_X(q.u+
30,d.height)),a=new tn_X(q.u+30+-4,d.height+-4),c=0;c<q.l.length;++c)tn_4c(q.l[c],a)}q.ea(f);q.C()})}else l={images:b[0].images||{},textWidth:b[0].textWidth||0,offset:b[0].offset||0,name:b[0].name,contentElem:b[0].contentElem,onclick:b[0].onclick},this.f.push(l),this.C()};tn_3.prototype.Sa=function(){for(var a=new tn_X(this.p.width+-4,this.p.height+-4),b=0;b<this.l.length;b++){var c=this.l[b];tn_4c(c,a)}};tn_3.prototype.Ma=function(a,b,c){this.r=a;this.Da=b;this.Ua=c;tn_7c(this.g.maximize)};
tn_3.prototype.na=function(){var a=this.l;tn_jd(a,tn_U);tn_vd(a);a=this.P;tn_jd(a,tn_U);tn_vd(a);this.s=0};tn_3.prototype.T=function(a){return new tn_X(tn_S(a.width,32),tn_S(a.height,0))};tn_3.prototype.xa=function(){this.P=[];this.ha=[];this.u=0};tn_3.prototype.ea=function(a){tn_me(this.f[this.s].labelNode);this.s=a;tn_ne(this.f[a].labelNode)};function tn_ne(a){var b=a.style;b.color="";b.textDecoration="";tn_T(a,"")}
function tn_me(a){var b=a.style;b.color="#0000cc";b.textDecoration="underline";tn_T(a,"pointer")}function tn_le(a,b,c){b=tn_J("div",b,null,null,!1,!0);for(var d=0;d<c.length;d++){var e=c[d],f=new tn_X(e[1],e[2]),h=new tn_a(e[3],e[4]),p=tn_0c+e[0]+".png",f=tn_Bd(p,b,h,f,!0,!0);a[e[5]||e[0]]=f}return b}
function tn_4(a,b,c,d,e,f){if(1==tn_V.type&&7>tn_V.version)return b=tn_Bd(tn_0c+c+(f?".gif":".png"),b,new tn_a(0,0),d,!0,!0),a[e||c]=b;tn_je||(tn_je=!0,d=document.createElement("link"),d.rel="stylesheet",d.type="text/css",d.href=tn_0c+"iw_sprite.css",document.getElementsByTagName("head")[0].appendChild(d));d=document.createElement("div");d.className="SPRITE_"+c;d.style.overflow="hidden";b.appendChild(d);return a[e||c]=d};if(window.jstiming){window.jstiming.ma={};window.jstiming.Xa=1;var tn_oe=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c))return d=a.t[b][0],e=void 0!=c?c:e[0],d-e},tn_pe=function(a,b,c){var d="";window.jstiming.pt&&(d+="&srt="+window.jstiming.pt,delete window.jstiming.pt);try{window.external&&window.external.tran?d+="&tran="+window.external.tran:window.gtbExternal&&window.gtbExternal.tran?d+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(d+="&tran="+window.chrome.csi().tran)}catch(e){}var f=
window.chrome;if(f&&(f=f.loadTimes)){f().wasFetchedViaSpdy&&(d+="&p=s");if(f().wasNpnNegotiated){var d=d+"&npn=1",h=f().npnNegotiatedProtocol;h&&(d+="&npnv="+(encodeURIComponent||escape)(h))}f().wasAlternateProtocolAvailable&&(d+="&apa=1")}var p=a.t,m=p.start,f=[],h=[],l;for(l in p)if("start"!=l&&0!=l.indexOf("_")){var g=p[l][1];g?p[g]&&h.push(l+"."+tn_oe(a,l,p[g][0])):m&&f.push(l+"."+tn_oe(a,l))}delete p.start;if(b)for(var k in b)d+="&"+k+"="+b[k];(b=c)||(b="https:"==document.location.protocol?"https://csi.gstatic.com/csi":
"http://csi.gstatic.com/csi");return a=[b,"?v=3","&s="+(window.jstiming.sn||"translate")+"&action=",a.name,h.length?"&it="+h.join(","):"",d,"&rt=",f.join(",")].join("")},tn_qe=function(a,b,c){a=tn_pe(a,b,c);if(!a)return"";b=new Image;var d=window.jstiming.Xa++;window.jstiming.ma[d]=b;b.onload=b.onerror=function(){window.jstiming&&delete window.jstiming.ma[d]};b.src=a;b=null;return a},tn_re=function(a,b,c){if("prerender"==document.webkitVisibilityState)return!1;tn_qe(a,b,c);return!0};window.jstiming.report=
function(a,b,c){if("prerender"==document.webkitVisibilityState){var d="webkitvisibilitychange",e=!1,f=function(){e||(b?b.prerender="1":b={prerender:"1"},tn_re(a,b,c)&&(e=!0,document.removeEventListener(d,f,!1)))};document.addEventListener(d,f,!1);return""}return tn_qe(a,b,c)}};var tn_5,tn_6=null,tn_7,tn_se,tn_te,tn_ue=!1,tn_ve=!1,tn_8=!1,tn_9=!1,tn_we={right:"left",left:"right",ltr:"rtl",rtl:"ltr"};function tn_xe(a){return a.substring(0,1).toUpperCase()+a.substring(1)}
var _intlStrings={_originalText:"Original Text:",_interfaceDirection:"ltr",_interfaceAlign:"left",_langpair:"",_currentBy:"",_unknown:"unknown",_suggestTranslation:"Suggest a translation",_submit:"Submit",_feedbackUrl:"http://translate.google.com/translate_suggestion",_suggestThanks:"Thank you for helping us improve the quality of our translations.",_reverse:!1};
function tn_ye(a){if(3==a.nodeType)return a.nodeValue;if(1==a.nodeType){for(var b="",c=0;c<a.childNodes.length;++c)b+=tn_ye(a.childNodes[c]);return b}return""}function tn_ze(a,b){if(a)if(3==b.nodeType)a.appendChild(document.createTextNode(b.nodeValue));else if(1==b.nodeType){var c;if("a"===b.nodeName||"A"===b.nodeName){c=document.createElement("a");var d=b.getAttribute("href");d&&c.setAttribute("href",d);a.appendChild(c)}else c=a;for(d=0;d<b.childNodes.length;++d)tn_ze(c,b.childNodes[d])}}
function _setupIW(){if(!tn_ue){tn_5=new tn_3;tn_7=document.createElement("div");tn_7.id="google-infowindow";tn_7.className="notranslate";tn_se=document.createElement("span");tn_7.onmouseover=tn_Ae;tn_7.onmouseout=tn_Be;document.body.appendChild(tn_se);document.body.appendChild(tn_7);var a=document.createElement("div");document.body.appendChild(a);tn_(a);a.innerHTML='<iframe id="google-feedback-frame" name="google-feedback-frame"></iframe>';tn_5.create(tn_7,tn_se);tn_7.firstChild.style.zIndex=2147483647;
tn_se.firstChild.style.zIndex=2147483647;tn_5.O(!0);tn_5.za(!0);tn_5.Ba(!0);tn_5.ja(!0);tn_5.ka(!1);tn_5.La(_intlStrings._interfaceDirection);tn_Yd(tn_5,tn_Pd,function(){tn_Be(!0);tn_9&&tn_Ce(!1)});var b=document.getElementById("gt-nvframe");b&&window.addEventListener("scroll",function(){b.style.top=-document.body.scrollTop+"px"},!1);tn_ue=!0}}var tn_$=null;function tn_Ae(){tn_ve=!0;tn_De(tn_6)}
function tn_De(a){if(a&&(null!==tn_$&&(window.clearTimeout(tn_$),tn_$=null),!tn_8))if(tn_6==a)tn_9||(tn_te=tn_6.style.backgroundColor,tn_6.style.backgroundColor="#E6ECF9");else{tn_9&&(tn_5.restore(!0),tn_9=!1);for(var b,c=a.cloneNode(!0),d=a.childNodes.length-1;0<=d;--d)"google-src-text"==a.childNodes[d].className&&(b=a.childNodes[d].cloneNode(!0),c.removeChild(c.childNodes[d]),b.className="google-src-active-text");if(b){tn_5.O(!0);tn_te=a.style.backgroundColor;a.style.backgroundColor="#E6ECF9";var e=
document.createElement("div"),d=document.createElement("div"),f=document.createElement("img"),h=document.createElement("div");h.appendChild(f);f.width=48;f.height=17;f.border=0;f.style.display="inline";f.style.padding="0px";f.style.border="0px solid black";h.style.margin="0px";h.style.marginBottom="-17px";h.style.padding="0px";h.style.textAlign=tn_we[_intlStrings._interfaceAlign];f.src="http://www.google.com/images/logo_smallest.png";f.style["margin"+tn_xe(_intlStrings._interfaceAlign)]="6px";f.style["margin"+
tn_xe(tn_we[_intlStrings._interfaceAlign])]=tn_M(18);e.appendChild(h);e.appendChild(d);d.appendChild(document.createTextNode(_intlStrings._originalText));d.style.color="#333";d.style.direction=_intlStrings._interfaceDirection;d.style.textAlign=_intlStrings._interfaceAlign;d.style.fontWeight="bold";d.style.fontSize="12px";d.style.minHeight="19px";d.style.fontFamily="arial,sans-serif";d.style["margin"+tn_xe(tn_we[_intlStrings._interfaceAlign])]=tn_M(72);d=document.createElement("div");d.className="google-src-active-text";
d.style.lineHeight="19px";d.style.direction=_intlStrings._interfaceDirection;d.style.textAlign=_intlStrings._interfaceAlign;tn_ze(d,b);e.appendChild(d);e.style.zIndex=2147483647;if(0==_intlStrings._langpair.length)tn_6=a,tn_zd(e,function(a){tn_5.hide();tn_5.A(a,[new tn_ke(_intlStrings._originalText,e)]);tn_5.M(tn_6);tn_5.show()},(document.width||document.body.scrollWidth)/2);else{var d=e.cloneNode(!0),p=document.createElement("div");p.appendChild(d);d=document.createElement("div");f=document.createElement("span");
h=document.createElement("div");h.style.direction=_intlStrings._interfaceDirection;h.style.textAlign=_intlStrings._interfaceAlign;h.style.marginTop=tn_M(5);d.appendChild(h);var m=document.createElement("img");m.src="http://www.google.com/images/zippy_plus_sm.gif";m.width=12;m.height=12;m.border=0;m.style.border="none";m.style.verticalAlign="middle";h.appendChild(m);h.appendChild(document.createTextNode(" "));h.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._suggestTranslation));
f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.color="#0000CC";f.style.textDecoration="underline";f.style.fontFamily="arial,sans-serif";f.style.fontSize="12px";h.onclick=tn_Ee;tn_T(f,"pointer");e.appendChild(d);var l=document.createElement("div"),d=document.createElement("div"),f=document.createElement("span");d.style.direction=_intlStrings._interfaceDirection;d.style.textAlign=_intlStrings._interfaceAlign;d.style.marginTop=tn_M(5);d.style.marginBottom=
tn_M(6);l.appendChild(d);h=document.createElement("img");h.src="http://www.google.com/images/zippy_minus_sm.gif";h.width=12;h.height=12;h.border=0;h.style.border="none";h.style.verticalAlign="middle";d.appendChild(h);d.appendChild(document.createTextNode(" "));d.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._suggestTranslation));f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.color="#0000CC";f.style.textDecoration="underline";
f.style.fontFamily="arial,sans-serif";f.style.fontSize="12px";d.onclick=function(){tn_Ce(!0)};tn_T(f,"pointer");tn_6=a;a=document.createElement("div");d=document.createElement("form");d.style.marginBottom="0px";d.style.paddingBottom="0px";d.target="google-feedback-frame";d.method="post";d.action=_intlStrings._feedbackUrl;a.appendChild(d);var g=document.createElement("input");g.type="hidden";g.name="gtrans";d.appendChild(g);_intlStrings._reverse?(f=tn_ye(c),c=tn_ye(b)):(c=tn_ye(c),f=tn_ye(b));g.value=
c;b=document.createElement("input");b.type="hidden";b.value=f;b.name="text";d.appendChild(b);b=document.createElement("input");b.name="langpair";b.type="hidden";b.value=_intlStrings._langpair;d.appendChild(b);b=document.createElement("input");b.name="u";b.type="hidden";b.value=tn_Fe("u");d.appendChild(b);b=document.createElement("input");b.name="oe";b.type="hidden";if(document.charset)b.value=document.charset,d.appendChild(b);else if(document.characterSet)b.value=document.characterSet,d.appendChild(b);
else if(f=tn_Fe("oe"))d.appendChild(b),b.value=f;var k=document.createElement("textarea");k.rows=3;k.name="utrans";k.value=c;d.appendChild(k);b=document.createElement("div");b.style.direction=_intlStrings._interfaceDirection;b.style.textAlign=tn_we[_intlStrings._interfaceAlign];b.style.marginTop=tn_M(6);b.style.marginBottom="0px";d.appendChild(b);c=document.createElement("input");c.type="submit";c.value=_intlStrings._submit;b.appendChild(c);var q=document.createElement("div");q.appendChild(document.createElement("hr"));
q.appendChild(document.createTextNode(_intlStrings._suggestThanks));q.style.direction=_intlStrings._interfaceDirection;q.style.textAlign=_intlStrings._interfaceAlign;q.style.fontFamily="arial,sans-serif";q.style.fontSize="12px";q.style.overflow="auto";q.style.marginTop="10px";tn_(q);l.appendChild(a);p.appendChild(l);p.appendChild(q);d.onsubmit=function(){window.setTimeout(function(){tn_(l);tn_Q(q)},1);tn_8=!1;return k.value!=g.value};tn_Ad([p,e],function(a){k.style.width=tn_M(a[0].width-6);k.style.padding=
tn_M(2);tn_5.hide();tn_5.A(a[1],[new tn_ke(_intlStrings._originalText,e)]);tn_5.Ma(a[0],[new tn_ke(_intlStrings._originalText,p)]);tn_5.M(tn_6);tn_5.O(!0);tn_5.show()},(document.width||document.body.scrollWidth)/2)}}}}function tn_Fe(a){for(var b=window.location.search.substring(1),b=b.split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0].toLowerCase()==a&&0<d.length)return window.unescape(d[1])}return""}
function tn_Ge(a){tn_ue&&(tn_ve=!0,tn_8||(null!==tn_$&&(window.clearTimeout(tn_$),tn_$=null),tn_6==a?(tn_te=tn_6.style.backgroundColor,tn_6.style.backgroundColor="#E6ECF9"):tn_$=window.setTimeout(function(){tn_De(a)},500)))}function tn_Be(a){tn_ue&&(!0!==a&&(tn_ve=!1),tn_8||(tn_6&&tn_6.style&&(tn_6.style.backgroundColor=tn_te),tn_$&&(window.clearTimeout(tn_$),tn_$=null),!0!==a?tn_$=window.setTimeout(tn_He,250):tn_He()))}
function tn_He(){tn_8||(tn_5.hide(),tn_9&&(tn_5.restore(!0),tn_9=!1),tn_6=null)}function tn_Ee(){tn_9=tn_8=!0;var a=tn_Yd(tn_5,tn_Sd,function(){tn_Zd(a)});tn_5.maximize()}function tn_Ce(a){var b=tn_Yd(tn_5,tn_Td,function(){tn_Zd(b);tn_9=!1;a?window.setTimeout(function(){tn_8=!1;tn_ve||tn_Be(!0)},500):(tn_8=!1,tn_ve||tn_Be(!0))});tn_5.restore()}
function _csi(a,b){var c={};c.sl=a;c.tl=b;var d=window.jstiming.load;d.tick("prt");d.tick("ol");d.name="w";window.jstiming.sn="translate";window.jstiming.report(d,c);try{window.external&&window.external.resT()}catch(e){}}function tn_Ie(a){var b=window.onload;window.onload=b?function(){try{a()}catch(c){}b()}:a}var _tipon=tn_Ge,_tipoff=tn_Be,_addload=tn_Ie,tn_Je=window.jstiming.load;tn_Je.tick("jl");
